//! Table-driven clipboard watch cases (#77).

use ronin_core::{
    clipboard_watch_proposal_may_inject_into_chat_request,
    confirmed_clipboard_attach_may_inject_into_chat_request, ClipboardObserveOutcome,
    ClipboardWatchController, ClipboardWatchPrefs,
};

struct ObserveCase {
    name: &'static str,
    enable_baseline: Option<&'static str>,
    observe: &'static str,
    expect: ClipboardObserveOutcome,
    expect_pending: bool,
}

fn run_observe(case: &ObserveCase) {
    let mut watch = ClipboardWatchController::new();
    if let Some(base) = case.enable_baseline {
        watch.enable(Some(base));
    }
    let outcome = watch.observe_text(case.observe);
    assert_eq!(outcome, case.expect, "case {}", case.name);
    assert_eq!(
        watch.pending_proposal().is_some(),
        case.expect_pending,
        "case {} pending",
        case.name
    );
    assert!(!clipboard_watch_proposal_may_inject_into_chat_request());
}

#[test]
fn table_disabled_and_empty_cases() {
    let cases = [
        ObserveCase {
            name: "disabled_000",
            enable_baseline: None,
            observe: "disabled payload 000 token=leak0",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_001",
            enable_baseline: None,
            observe: "disabled payload 001 token=leak1",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_002",
            enable_baseline: None,
            observe: "disabled payload 002 token=leak2",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_003",
            enable_baseline: None,
            observe: "disabled payload 003 token=leak3",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_004",
            enable_baseline: None,
            observe: "disabled payload 004 token=leak4",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_005",
            enable_baseline: None,
            observe: "disabled payload 005 token=leak5",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_006",
            enable_baseline: None,
            observe: "disabled payload 006 token=leak6",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_007",
            enable_baseline: None,
            observe: "disabled payload 007 token=leak7",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_008",
            enable_baseline: None,
            observe: "disabled payload 008 token=leak8",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_009",
            enable_baseline: None,
            observe: "disabled payload 009 token=leak9",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_010",
            enable_baseline: None,
            observe: "disabled payload 010 token=leak10",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_011",
            enable_baseline: None,
            observe: "disabled payload 011 token=leak11",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_012",
            enable_baseline: None,
            observe: "disabled payload 012 token=leak12",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_013",
            enable_baseline: None,
            observe: "disabled payload 013 token=leak13",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_014",
            enable_baseline: None,
            observe: "disabled payload 014 token=leak14",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_015",
            enable_baseline: None,
            observe: "disabled payload 015 token=leak15",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_016",
            enable_baseline: None,
            observe: "disabled payload 016 token=leak16",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_017",
            enable_baseline: None,
            observe: "disabled payload 017 token=leak17",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_018",
            enable_baseline: None,
            observe: "disabled payload 018 token=leak18",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_019",
            enable_baseline: None,
            observe: "disabled payload 019 token=leak19",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_020",
            enable_baseline: None,
            observe: "disabled payload 020 token=leak20",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_021",
            enable_baseline: None,
            observe: "disabled payload 021 token=leak21",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_022",
            enable_baseline: None,
            observe: "disabled payload 022 token=leak22",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_023",
            enable_baseline: None,
            observe: "disabled payload 023 token=leak23",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_024",
            enable_baseline: None,
            observe: "disabled payload 024 token=leak24",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_025",
            enable_baseline: None,
            observe: "disabled payload 025 token=leak25",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_026",
            enable_baseline: None,
            observe: "disabled payload 026 token=leak26",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_027",
            enable_baseline: None,
            observe: "disabled payload 027 token=leak27",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_028",
            enable_baseline: None,
            observe: "disabled payload 028 token=leak28",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_029",
            enable_baseline: None,
            observe: "disabled payload 029 token=leak29",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_030",
            enable_baseline: None,
            observe: "disabled payload 030 token=leak30",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_031",
            enable_baseline: None,
            observe: "disabled payload 031 token=leak31",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_032",
            enable_baseline: None,
            observe: "disabled payload 032 token=leak32",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_033",
            enable_baseline: None,
            observe: "disabled payload 033 token=leak33",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_034",
            enable_baseline: None,
            observe: "disabled payload 034 token=leak34",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_035",
            enable_baseline: None,
            observe: "disabled payload 035 token=leak35",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_036",
            enable_baseline: None,
            observe: "disabled payload 036 token=leak36",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_037",
            enable_baseline: None,
            observe: "disabled payload 037 token=leak37",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_038",
            enable_baseline: None,
            observe: "disabled payload 038 token=leak38",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
        ObserveCase {
            name: "disabled_039",
            enable_baseline: None,
            observe: "disabled payload 039 token=leak39",
            expect: ClipboardObserveOutcome::IgnoredDisabled,
            expect_pending: false,
        },
    ];
    for case in &cases {
        run_observe(case);
    }
}

#[test]
fn table_enabled_change_and_unchanged_cases() {
    let cases = [
        ObserveCase {
            name: "unchanged_000",
            enable_baseline: Some("base-000"),
            observe: "base-000",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_001",
            enable_baseline: Some("base-001"),
            observe: "base-001",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_002",
            enable_baseline: Some("base-002"),
            observe: "base-002",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_003",
            enable_baseline: Some("base-003"),
            observe: "base-003",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_004",
            enable_baseline: Some("base-004"),
            observe: "base-004",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_005",
            enable_baseline: Some("base-005"),
            observe: "base-005",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_006",
            enable_baseline: Some("base-006"),
            observe: "base-006",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_007",
            enable_baseline: Some("base-007"),
            observe: "base-007",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_008",
            enable_baseline: Some("base-008"),
            observe: "base-008",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_009",
            enable_baseline: Some("base-009"),
            observe: "base-009",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_010",
            enable_baseline: Some("base-010"),
            observe: "base-010",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_011",
            enable_baseline: Some("base-011"),
            observe: "base-011",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_012",
            enable_baseline: Some("base-012"),
            observe: "base-012",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_013",
            enable_baseline: Some("base-013"),
            observe: "base-013",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_014",
            enable_baseline: Some("base-014"),
            observe: "base-014",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_015",
            enable_baseline: Some("base-015"),
            observe: "base-015",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_016",
            enable_baseline: Some("base-016"),
            observe: "base-016",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_017",
            enable_baseline: Some("base-017"),
            observe: "base-017",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_018",
            enable_baseline: Some("base-018"),
            observe: "base-018",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_019",
            enable_baseline: Some("base-019"),
            observe: "base-019",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_020",
            enable_baseline: Some("base-020"),
            observe: "base-020",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_021",
            enable_baseline: Some("base-021"),
            observe: "base-021",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_022",
            enable_baseline: Some("base-022"),
            observe: "base-022",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_023",
            enable_baseline: Some("base-023"),
            observe: "base-023",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_024",
            enable_baseline: Some("base-024"),
            observe: "base-024",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_025",
            enable_baseline: Some("base-025"),
            observe: "base-025",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_026",
            enable_baseline: Some("base-026"),
            observe: "base-026",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_027",
            enable_baseline: Some("base-027"),
            observe: "base-027",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_028",
            enable_baseline: Some("base-028"),
            observe: "base-028",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_029",
            enable_baseline: Some("base-029"),
            observe: "base-029",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_030",
            enable_baseline: Some("base-030"),
            observe: "base-030",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_031",
            enable_baseline: Some("base-031"),
            observe: "base-031",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_032",
            enable_baseline: Some("base-032"),
            observe: "base-032",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_033",
            enable_baseline: Some("base-033"),
            observe: "base-033",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_034",
            enable_baseline: Some("base-034"),
            observe: "base-034",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_035",
            enable_baseline: Some("base-035"),
            observe: "base-035",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_036",
            enable_baseline: Some("base-036"),
            observe: "base-036",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_037",
            enable_baseline: Some("base-037"),
            observe: "base-037",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_038",
            enable_baseline: Some("base-038"),
            observe: "base-038",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_039",
            enable_baseline: Some("base-039"),
            observe: "base-039",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_040",
            enable_baseline: Some("base-040"),
            observe: "base-040",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_041",
            enable_baseline: Some("base-041"),
            observe: "base-041",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_042",
            enable_baseline: Some("base-042"),
            observe: "base-042",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_043",
            enable_baseline: Some("base-043"),
            observe: "base-043",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_044",
            enable_baseline: Some("base-044"),
            observe: "base-044",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_045",
            enable_baseline: Some("base-045"),
            observe: "base-045",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_046",
            enable_baseline: Some("base-046"),
            observe: "base-046",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_047",
            enable_baseline: Some("base-047"),
            observe: "base-047",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_048",
            enable_baseline: Some("base-048"),
            observe: "base-048",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_049",
            enable_baseline: Some("base-049"),
            observe: "base-049",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_050",
            enable_baseline: Some("base-050"),
            observe: "base-050",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_051",
            enable_baseline: Some("base-051"),
            observe: "base-051",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_052",
            enable_baseline: Some("base-052"),
            observe: "base-052",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_053",
            enable_baseline: Some("base-053"),
            observe: "base-053",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_054",
            enable_baseline: Some("base-054"),
            observe: "base-054",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_055",
            enable_baseline: Some("base-055"),
            observe: "base-055",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_056",
            enable_baseline: Some("base-056"),
            observe: "base-056",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_057",
            enable_baseline: Some("base-057"),
            observe: "base-057",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_058",
            enable_baseline: Some("base-058"),
            observe: "base-058",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "unchanged_059",
            enable_baseline: Some("base-059"),
            observe: "base-059",
            expect: ClipboardObserveOutcome::Unchanged,
            expect_pending: false,
        },
        ObserveCase {
            name: "changed_000",
            enable_baseline: Some("base-chg-000"),
            observe: "changed-text-000-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_001",
            enable_baseline: Some("base-chg-001"),
            observe: "changed-text-001-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_002",
            enable_baseline: Some("base-chg-002"),
            observe: "changed-text-002-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_003",
            enable_baseline: Some("base-chg-003"),
            observe: "changed-text-003-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_004",
            enable_baseline: Some("base-chg-004"),
            observe: "changed-text-004-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_005",
            enable_baseline: Some("base-chg-005"),
            observe: "changed-text-005-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_006",
            enable_baseline: Some("base-chg-006"),
            observe: "changed-text-006-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_007",
            enable_baseline: Some("base-chg-007"),
            observe: "changed-text-007-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_008",
            enable_baseline: Some("base-chg-008"),
            observe: "changed-text-008-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_009",
            enable_baseline: Some("base-chg-009"),
            observe: "changed-text-009-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_010",
            enable_baseline: Some("base-chg-010"),
            observe: "changed-text-010-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_011",
            enable_baseline: Some("base-chg-011"),
            observe: "changed-text-011-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_012",
            enable_baseline: Some("base-chg-012"),
            observe: "changed-text-012-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_013",
            enable_baseline: Some("base-chg-013"),
            observe: "changed-text-013-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_014",
            enable_baseline: Some("base-chg-014"),
            observe: "changed-text-014-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_015",
            enable_baseline: Some("base-chg-015"),
            observe: "changed-text-015-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_016",
            enable_baseline: Some("base-chg-016"),
            observe: "changed-text-016-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_017",
            enable_baseline: Some("base-chg-017"),
            observe: "changed-text-017-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_018",
            enable_baseline: Some("base-chg-018"),
            observe: "changed-text-018-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_019",
            enable_baseline: Some("base-chg-019"),
            observe: "changed-text-019-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_020",
            enable_baseline: Some("base-chg-020"),
            observe: "changed-text-020-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_021",
            enable_baseline: Some("base-chg-021"),
            observe: "changed-text-021-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_022",
            enable_baseline: Some("base-chg-022"),
            observe: "changed-text-022-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_023",
            enable_baseline: Some("base-chg-023"),
            observe: "changed-text-023-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_024",
            enable_baseline: Some("base-chg-024"),
            observe: "changed-text-024-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_025",
            enable_baseline: Some("base-chg-025"),
            observe: "changed-text-025-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_026",
            enable_baseline: Some("base-chg-026"),
            observe: "changed-text-026-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_027",
            enable_baseline: Some("base-chg-027"),
            observe: "changed-text-027-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_028",
            enable_baseline: Some("base-chg-028"),
            observe: "changed-text-028-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_029",
            enable_baseline: Some("base-chg-029"),
            observe: "changed-text-029-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_030",
            enable_baseline: Some("base-chg-030"),
            observe: "changed-text-030-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_031",
            enable_baseline: Some("base-chg-031"),
            observe: "changed-text-031-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_032",
            enable_baseline: Some("base-chg-032"),
            observe: "changed-text-032-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_033",
            enable_baseline: Some("base-chg-033"),
            observe: "changed-text-033-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_034",
            enable_baseline: Some("base-chg-034"),
            observe: "changed-text-034-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_035",
            enable_baseline: Some("base-chg-035"),
            observe: "changed-text-035-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_036",
            enable_baseline: Some("base-chg-036"),
            observe: "changed-text-036-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_037",
            enable_baseline: Some("base-chg-037"),
            observe: "changed-text-037-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_038",
            enable_baseline: Some("base-chg-038"),
            observe: "changed-text-038-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_039",
            enable_baseline: Some("base-chg-039"),
            observe: "changed-text-039-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_040",
            enable_baseline: Some("base-chg-040"),
            observe: "changed-text-040-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_041",
            enable_baseline: Some("base-chg-041"),
            observe: "changed-text-041-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_042",
            enable_baseline: Some("base-chg-042"),
            observe: "changed-text-042-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_043",
            enable_baseline: Some("base-chg-043"),
            observe: "changed-text-043-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_044",
            enable_baseline: Some("base-chg-044"),
            observe: "changed-text-044-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_045",
            enable_baseline: Some("base-chg-045"),
            observe: "changed-text-045-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_046",
            enable_baseline: Some("base-chg-046"),
            observe: "changed-text-046-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_047",
            enable_baseline: Some("base-chg-047"),
            observe: "changed-text-047-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_048",
            enable_baseline: Some("base-chg-048"),
            observe: "changed-text-048-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_049",
            enable_baseline: Some("base-chg-049"),
            observe: "changed-text-049-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_050",
            enable_baseline: Some("base-chg-050"),
            observe: "changed-text-050-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_051",
            enable_baseline: Some("base-chg-051"),
            observe: "changed-text-051-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_052",
            enable_baseline: Some("base-chg-052"),
            observe: "changed-text-052-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_053",
            enable_baseline: Some("base-chg-053"),
            observe: "changed-text-053-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_054",
            enable_baseline: Some("base-chg-054"),
            observe: "changed-text-054-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_055",
            enable_baseline: Some("base-chg-055"),
            observe: "changed-text-055-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_056",
            enable_baseline: Some("base-chg-056"),
            observe: "changed-text-056-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_057",
            enable_baseline: Some("base-chg-057"),
            observe: "changed-text-057-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_058",
            enable_baseline: Some("base-chg-058"),
            observe: "changed-text-058-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "changed_059",
            enable_baseline: Some("base-chg-059"),
            observe: "changed-text-059-api_key=should-scrub-in-preview",
            expect: ClipboardObserveOutcome::Proposed,
            expect_pending: true,
        },
        ObserveCase {
            name: "empty_000",
            enable_baseline: Some("base-empty-000"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_001",
            enable_baseline: Some("base-empty-001"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_002",
            enable_baseline: Some("base-empty-002"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_003",
            enable_baseline: Some("base-empty-003"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_004",
            enable_baseline: Some("base-empty-004"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_005",
            enable_baseline: Some("base-empty-005"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_006",
            enable_baseline: Some("base-empty-006"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_007",
            enable_baseline: Some("base-empty-007"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_008",
            enable_baseline: Some("base-empty-008"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_009",
            enable_baseline: Some("base-empty-009"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_010",
            enable_baseline: Some("base-empty-010"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_011",
            enable_baseline: Some("base-empty-011"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_012",
            enable_baseline: Some("base-empty-012"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_013",
            enable_baseline: Some("base-empty-013"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_014",
            enable_baseline: Some("base-empty-014"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_015",
            enable_baseline: Some("base-empty-015"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_016",
            enable_baseline: Some("base-empty-016"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_017",
            enable_baseline: Some("base-empty-017"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_018",
            enable_baseline: Some("base-empty-018"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
        ObserveCase {
            name: "empty_019",
            enable_baseline: Some("base-empty-019"),
            observe: "   ",
            expect: ClipboardObserveOutcome::IgnoredEmpty,
            expect_pending: false,
        },
    ];
    for case in &cases {
        run_observe(case);
    }
}

#[test]
fn confirm_and_dismiss_matrix() {
    for i in 0..80usize {
        let mut watch = ClipboardWatchController::new();
        watch.enable(Some(&format!("b{i}")));
        let text = format!("payload-{i}-value");
        assert_eq!(watch.observe_text(&text), ClipboardObserveOutcome::Proposed);
        if i % 2 == 0 {
            let draft = watch.confirm_pending().expect("draft");
            assert!(draft.context_block.contains(&text));
            assert!(confirmed_clipboard_attach_may_inject_into_chat_request());
            assert!(watch.pending_proposal().is_none());
        } else {
            watch.dismiss_pending();
            assert!(watch.pending_proposal().is_none());
            assert!(watch.confirm_pending().is_none());
        }
    }
}

#[test]
fn disable_after_propose_matrix() {
    for i in 0..60usize {
        let mut watch = ClipboardWatchController::new();
        watch.enable(Some("x"));
        watch.observe_text(&format!("p{i}"));
        assert!(watch.pending_proposal().is_some());
        watch.disable();
        assert!(!watch.is_enabled());
        assert!(watch.pending_proposal().is_none());
        assert_eq!(
            watch.observe_text(&format!("after-{i}")),
            ClipboardObserveOutcome::IgnoredDisabled
        );
        assert!(!ClipboardWatchPrefs::default().enabled);
    }
}
