//! Extra table-driven notification shaping cases (#75).

use ronin_core::{
    shape_generation_notification, GenerationNotifyInput, GenerationNotifyKind, NotificationPrefs,
    AMBIENT_REDACTED, FOCUS_THREAD_ACTION,
};

struct Row {
    name: &'static str,
    enabled: bool,
    kind: GenerationNotifyKind,
    thread_id: &'static str,
    title: Option<&'static str>,
    err: Option<&'static str>,
    expect: bool,
    body_has: Option<&'static str>,
    body_lacks: Option<&'static str>,
}

#[test]
fn extra_shape_rows() {
    let rows: &[Row] = &[
        Row {
            name: "row_000",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "",
            title: Some("api_key=extra-secret-0"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_001",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-1",
            title: Some("Plan 1"),
            err: Some("timeout 1"),
            expect: true,
            body_has: Some("Plan 1"),
            body_lacks: None,
        },
        Row {
            name: "row_002",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-2",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_003",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-3",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_004",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-4",
            title: Some("password=pw4"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw4"),
        },
        Row {
            name: "row_005",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-5",
            title: Some("Thread 5"),
            err: Some("access_token=at5"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_006",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-6",
            title: Some("secret=s6"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s6"),
        },
        Row {
            name: "row_007",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-7",
            title: Some("api_key=extra-secret-7"),
            err: Some("token=extra-token-7"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-7"),
        },
        Row {
            name: "row_008",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-8",
            title: Some("Plan 8"),
            err: None,
            expect: true,
            body_has: Some("Plan 8"),
            body_lacks: None,
        },
        Row {
            name: "row_009",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-9",
            title: None,
            err: Some("Bearer sk-extra9"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra9"),
        },
        Row {
            name: "row_010",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-10",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_011",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-11",
            title: Some("password=pw11"),
            err: Some("key=k11"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw11"),
        },
        Row {
            name: "row_012",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-12",
            title: Some("Thread 12"),
            err: None,
            expect: true,
            body_has: Some("Thread 12"),
            body_lacks: None,
        },
        Row {
            name: "row_013",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-13",
            title: Some("secret=s13"),
            err: Some("plain error 13"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s13"),
        },
        Row {
            name: "row_014",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-14",
            title: Some("api_key=extra-secret-14"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-14"),
        },
        Row {
            name: "row_015",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-15",
            title: Some("Plan 15"),
            err: Some("timeout 15"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_016",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-16",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_017",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-17",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_018",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-18",
            title: Some("password=pw18"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw18"),
        },
        Row {
            name: "row_019",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-19",
            title: Some("Thread 19"),
            err: Some("access_token=at19"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at19"),
        },
        Row {
            name: "row_020",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-20",
            title: Some("secret=s20"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_021",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-21",
            title: Some("api_key=extra-secret-21"),
            err: Some("token=extra-token-21"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-21"),
        },
        Row {
            name: "row_022",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-22",
            title: Some("Plan 22"),
            err: None,
            expect: true,
            body_has: Some("Plan 22"),
            body_lacks: None,
        },
        Row {
            name: "row_023",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "",
            title: None,
            err: Some("Bearer sk-extra23"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_024",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-24",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_025",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-25",
            title: Some("password=pw25"),
            err: Some("key=k25"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_026",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-26",
            title: Some("Thread 26"),
            err: None,
            expect: true,
            body_has: Some("Thread 26"),
            body_lacks: None,
        },
        Row {
            name: "row_027",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-27",
            title: Some("secret=s27"),
            err: Some("plain error 27"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s27"),
        },
        Row {
            name: "row_028",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-28",
            title: Some("api_key=extra-secret-28"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-28"),
        },
        Row {
            name: "row_029",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-29",
            title: Some("Plan 29"),
            err: Some("timeout 29"),
            expect: true,
            body_has: Some("Plan 29"),
            body_lacks: None,
        },
        Row {
            name: "row_030",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-30",
            title: None,
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_031",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-31",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_032",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-32",
            title: Some("password=pw32"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw32"),
        },
        Row {
            name: "row_033",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-33",
            title: Some("Thread 33"),
            err: Some("access_token=at33"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at33"),
        },
        Row {
            name: "row_034",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-34",
            title: Some("secret=s34"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s34"),
        },
        Row {
            name: "row_035",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-35",
            title: Some("api_key=extra-secret-35"),
            err: Some("token=extra-token-35"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_036",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-36",
            title: Some("Plan 36"),
            err: None,
            expect: true,
            body_has: Some("Plan 36"),
            body_lacks: None,
        },
        Row {
            name: "row_037",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-37",
            title: None,
            err: Some("Bearer sk-extra37"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra37"),
        },
        Row {
            name: "row_038",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-38",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_039",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-39",
            title: Some("password=pw39"),
            err: Some("key=k39"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw39"),
        },
        Row {
            name: "row_040",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-40",
            title: Some("Thread 40"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_041",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-41",
            title: Some("secret=s41"),
            err: Some("plain error 41"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s41"),
        },
        Row {
            name: "row_042",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-42",
            title: Some("api_key=extra-secret-42"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-42"),
        },
        Row {
            name: "row_043",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-43",
            title: Some("Plan 43"),
            err: Some("timeout 43"),
            expect: true,
            body_has: Some("Plan 43"),
            body_lacks: None,
        },
        Row {
            name: "row_044",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-44",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_045",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-45",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_046",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "",
            title: Some("password=pw46"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_047",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-47",
            title: Some("Thread 47"),
            err: Some("access_token=at47"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at47"),
        },
        Row {
            name: "row_048",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-48",
            title: Some("secret=s48"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s48"),
        },
        Row {
            name: "row_049",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-49",
            title: Some("api_key=extra-secret-49"),
            err: Some("token=extra-token-49"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-49"),
        },
        Row {
            name: "row_050",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-50",
            title: Some("Plan 50"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_051",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-51",
            title: None,
            err: Some("Bearer sk-extra51"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra51"),
        },
        Row {
            name: "row_052",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-52",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_053",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-53",
            title: Some("password=pw53"),
            err: Some("key=k53"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw53"),
        },
        Row {
            name: "row_054",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-54",
            title: Some("Thread 54"),
            err: None,
            expect: true,
            body_has: Some("Thread 54"),
            body_lacks: None,
        },
        Row {
            name: "row_055",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-55",
            title: Some("secret=s55"),
            err: Some("plain error 55"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_056",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-56",
            title: Some("api_key=extra-secret-56"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-56"),
        },
        Row {
            name: "row_057",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-57",
            title: Some("Plan 57"),
            err: Some("timeout 57"),
            expect: true,
            body_has: Some("Plan 57"),
            body_lacks: None,
        },
        Row {
            name: "row_058",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-58",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_059",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-59",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_060",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-60",
            title: Some("password=pw60"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_061",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-61",
            title: Some("Thread 61"),
            err: Some("access_token=at61"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at61"),
        },
        Row {
            name: "row_062",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-62",
            title: Some("secret=s62"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s62"),
        },
        Row {
            name: "row_063",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-63",
            title: Some("api_key=extra-secret-63"),
            err: Some("token=extra-token-63"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-63"),
        },
        Row {
            name: "row_064",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-64",
            title: Some("Plan 64"),
            err: None,
            expect: true,
            body_has: Some("Plan 64"),
            body_lacks: None,
        },
        Row {
            name: "row_065",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-65",
            title: None,
            err: Some("Bearer sk-extra65"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_066",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-66",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_067",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-67",
            title: Some("password=pw67"),
            err: Some("key=k67"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw67"),
        },
        Row {
            name: "row_068",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-68",
            title: Some("Thread 68"),
            err: None,
            expect: true,
            body_has: Some("Thread 68"),
            body_lacks: None,
        },
        Row {
            name: "row_069",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "",
            title: Some("secret=s69"),
            err: Some("plain error 69"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_070",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-70",
            title: Some("api_key=extra-secret-70"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_071",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-71",
            title: Some("Plan 71"),
            err: Some("timeout 71"),
            expect: true,
            body_has: Some("Plan 71"),
            body_lacks: None,
        },
        Row {
            name: "row_072",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-72",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_073",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-73",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_074",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-74",
            title: Some("password=pw74"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw74"),
        },
        Row {
            name: "row_075",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-75",
            title: Some("Thread 75"),
            err: Some("access_token=at75"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_076",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-76",
            title: Some("secret=s76"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s76"),
        },
        Row {
            name: "row_077",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-77",
            title: Some("api_key=extra-secret-77"),
            err: Some("token=extra-token-77"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-77"),
        },
        Row {
            name: "row_078",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-78",
            title: Some("Plan 78"),
            err: None,
            expect: true,
            body_has: Some("Plan 78"),
            body_lacks: None,
        },
        Row {
            name: "row_079",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-79",
            title: None,
            err: Some("Bearer sk-extra79"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra79"),
        },
        Row {
            name: "row_080",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-80",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_081",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-81",
            title: Some("password=pw81"),
            err: Some("key=k81"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw81"),
        },
        Row {
            name: "row_082",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-82",
            title: Some("Thread 82"),
            err: None,
            expect: true,
            body_has: Some("Thread 82"),
            body_lacks: None,
        },
        Row {
            name: "row_083",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-83",
            title: Some("secret=s83"),
            err: Some("plain error 83"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s83"),
        },
        Row {
            name: "row_084",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-84",
            title: Some("api_key=extra-secret-84"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-84"),
        },
        Row {
            name: "row_085",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-85",
            title: Some("Plan 85"),
            err: Some("timeout 85"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_086",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-86",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_087",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-87",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_088",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-88",
            title: Some("password=pw88"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw88"),
        },
        Row {
            name: "row_089",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-89",
            title: Some("Thread 89"),
            err: Some("access_token=at89"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at89"),
        },
        Row {
            name: "row_090",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-90",
            title: Some("secret=s90"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_091",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-91",
            title: Some("api_key=extra-secret-91"),
            err: Some("token=extra-token-91"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-91"),
        },
        Row {
            name: "row_092",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "",
            title: Some("Plan 92"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_093",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-93",
            title: None,
            err: Some("Bearer sk-extra93"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra93"),
        },
        Row {
            name: "row_094",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-94",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_095",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-95",
            title: Some("password=pw95"),
            err: Some("key=k95"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_096",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-96",
            title: Some("Thread 96"),
            err: None,
            expect: true,
            body_has: Some("Thread 96"),
            body_lacks: None,
        },
        Row {
            name: "row_097",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-97",
            title: Some("secret=s97"),
            err: Some("plain error 97"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s97"),
        },
        Row {
            name: "row_098",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-98",
            title: Some("api_key=extra-secret-98"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-98"),
        },
        Row {
            name: "row_099",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-99",
            title: Some("Plan 99"),
            err: Some("timeout 99"),
            expect: true,
            body_has: Some("Plan 99"),
            body_lacks: None,
        },
        Row {
            name: "row_100",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-100",
            title: None,
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_101",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-101",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_102",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-102",
            title: Some("password=pw102"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw102"),
        },
        Row {
            name: "row_103",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-103",
            title: Some("Thread 103"),
            err: Some("access_token=at103"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at103"),
        },
        Row {
            name: "row_104",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-104",
            title: Some("secret=s104"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s104"),
        },
        Row {
            name: "row_105",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-105",
            title: Some("api_key=extra-secret-105"),
            err: Some("token=extra-token-105"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_106",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-106",
            title: Some("Plan 106"),
            err: None,
            expect: true,
            body_has: Some("Plan 106"),
            body_lacks: None,
        },
        Row {
            name: "row_107",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-107",
            title: None,
            err: Some("Bearer sk-extra107"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra107"),
        },
        Row {
            name: "row_108",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-108",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_109",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-109",
            title: Some("password=pw109"),
            err: Some("key=k109"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw109"),
        },
        Row {
            name: "row_110",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-110",
            title: Some("Thread 110"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_111",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-111",
            title: Some("secret=s111"),
            err: Some("plain error 111"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s111"),
        },
        Row {
            name: "row_112",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-112",
            title: Some("api_key=extra-secret-112"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-112"),
        },
        Row {
            name: "row_113",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-113",
            title: Some("Plan 113"),
            err: Some("timeout 113"),
            expect: true,
            body_has: Some("Plan 113"),
            body_lacks: None,
        },
        Row {
            name: "row_114",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-114",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_115",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_116",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-116",
            title: Some("password=pw116"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw116"),
        },
        Row {
            name: "row_117",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-117",
            title: Some("Thread 117"),
            err: Some("access_token=at117"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at117"),
        },
        Row {
            name: "row_118",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-118",
            title: Some("secret=s118"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s118"),
        },
        Row {
            name: "row_119",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-119",
            title: Some("api_key=extra-secret-119"),
            err: Some("token=extra-token-119"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-119"),
        },
        Row {
            name: "row_120",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-120",
            title: Some("Plan 120"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_121",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-121",
            title: None,
            err: Some("Bearer sk-extra121"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra121"),
        },
        Row {
            name: "row_122",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-122",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_123",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-123",
            title: Some("password=pw123"),
            err: Some("key=k123"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw123"),
        },
        Row {
            name: "row_124",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-124",
            title: Some("Thread 124"),
            err: None,
            expect: true,
            body_has: Some("Thread 124"),
            body_lacks: None,
        },
        Row {
            name: "row_125",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-125",
            title: Some("secret=s125"),
            err: Some("plain error 125"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_126",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-126",
            title: Some("api_key=extra-secret-126"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-126"),
        },
        Row {
            name: "row_127",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-127",
            title: Some("Plan 127"),
            err: Some("timeout 127"),
            expect: true,
            body_has: Some("Plan 127"),
            body_lacks: None,
        },
        Row {
            name: "row_128",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-128",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_129",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-129",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_130",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-130",
            title: Some("password=pw130"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_131",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-131",
            title: Some("Thread 131"),
            err: Some("access_token=at131"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at131"),
        },
        Row {
            name: "row_132",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-132",
            title: Some("secret=s132"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s132"),
        },
        Row {
            name: "row_133",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-133",
            title: Some("api_key=extra-secret-133"),
            err: Some("token=extra-token-133"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-133"),
        },
        Row {
            name: "row_134",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-134",
            title: Some("Plan 134"),
            err: None,
            expect: true,
            body_has: Some("Plan 134"),
            body_lacks: None,
        },
        Row {
            name: "row_135",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-135",
            title: None,
            err: Some("Bearer sk-extra135"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_136",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-136",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_137",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-137",
            title: Some("password=pw137"),
            err: Some("key=k137"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw137"),
        },
        Row {
            name: "row_138",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "",
            title: Some("Thread 138"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_139",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-139",
            title: Some("secret=s139"),
            err: Some("plain error 139"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s139"),
        },
        Row {
            name: "row_140",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-140",
            title: Some("api_key=extra-secret-140"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_141",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-141",
            title: Some("Plan 141"),
            err: Some("timeout 141"),
            expect: true,
            body_has: Some("Plan 141"),
            body_lacks: None,
        },
        Row {
            name: "row_142",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-142",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_143",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-143",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_144",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-144",
            title: Some("password=pw144"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw144"),
        },
        Row {
            name: "row_145",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-145",
            title: Some("Thread 145"),
            err: Some("access_token=at145"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_146",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-146",
            title: Some("secret=s146"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s146"),
        },
        Row {
            name: "row_147",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-147",
            title: Some("api_key=extra-secret-147"),
            err: Some("token=extra-token-147"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-147"),
        },
        Row {
            name: "row_148",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-148",
            title: Some("Plan 148"),
            err: None,
            expect: true,
            body_has: Some("Plan 148"),
            body_lacks: None,
        },
        Row {
            name: "row_149",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-149",
            title: None,
            err: Some("Bearer sk-extra149"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra149"),
        },
        Row {
            name: "row_150",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-150",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_151",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-151",
            title: Some("password=pw151"),
            err: Some("key=k151"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw151"),
        },
        Row {
            name: "row_152",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-152",
            title: Some("Thread 152"),
            err: None,
            expect: true,
            body_has: Some("Thread 152"),
            body_lacks: None,
        },
        Row {
            name: "row_153",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-153",
            title: Some("secret=s153"),
            err: Some("plain error 153"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s153"),
        },
        Row {
            name: "row_154",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-154",
            title: Some("api_key=extra-secret-154"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-154"),
        },
        Row {
            name: "row_155",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-155",
            title: Some("Plan 155"),
            err: Some("timeout 155"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_156",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-156",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_157",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-157",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_158",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-158",
            title: Some("password=pw158"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw158"),
        },
        Row {
            name: "row_159",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-159",
            title: Some("Thread 159"),
            err: Some("access_token=at159"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at159"),
        },
        Row {
            name: "row_160",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-160",
            title: Some("secret=s160"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_161",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "",
            title: Some("api_key=extra-secret-161"),
            err: Some("token=extra-token-161"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_162",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-162",
            title: Some("Plan 162"),
            err: None,
            expect: true,
            body_has: Some("Plan 162"),
            body_lacks: None,
        },
        Row {
            name: "row_163",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-163",
            title: None,
            err: Some("Bearer sk-extra163"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra163"),
        },
        Row {
            name: "row_164",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-164",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_165",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-165",
            title: Some("password=pw165"),
            err: Some("key=k165"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_166",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-166",
            title: Some("Thread 166"),
            err: None,
            expect: true,
            body_has: Some("Thread 166"),
            body_lacks: None,
        },
        Row {
            name: "row_167",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-167",
            title: Some("secret=s167"),
            err: Some("plain error 167"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s167"),
        },
        Row {
            name: "row_168",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-168",
            title: Some("api_key=extra-secret-168"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-168"),
        },
        Row {
            name: "row_169",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-169",
            title: Some("Plan 169"),
            err: Some("timeout 169"),
            expect: true,
            body_has: Some("Plan 169"),
            body_lacks: None,
        },
        Row {
            name: "row_170",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-170",
            title: None,
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_171",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-171",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
        Row {
            name: "row_172",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-172",
            title: Some("password=pw172"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw172"),
        },
        Row {
            name: "row_173",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-173",
            title: Some("Thread 173"),
            err: Some("access_token=at173"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at173"),
        },
        Row {
            name: "row_174",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-174",
            title: Some("secret=s174"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s174"),
        },
        Row {
            name: "row_175",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-175",
            title: Some("api_key=extra-secret-175"),
            err: Some("token=extra-token-175"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_176",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-176",
            title: Some("Plan 176"),
            err: None,
            expect: true,
            body_has: Some("Plan 176"),
            body_lacks: None,
        },
        Row {
            name: "row_177",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-177",
            title: None,
            err: Some("Bearer sk-extra177"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra177"),
        },
        Row {
            name: "row_178",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-178",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_179",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-179",
            title: Some("password=pw179"),
            err: Some("key=k179"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw179"),
        },
        Row {
            name: "row_180",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-180",
            title: Some("Thread 180"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_181",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-181",
            title: Some("secret=s181"),
            err: Some("plain error 181"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s181"),
        },
        Row {
            name: "row_182",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-182",
            title: Some("api_key=extra-secret-182"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-182"),
        },
        Row {
            name: "row_183",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-183",
            title: Some("Plan 183"),
            err: Some("timeout 183"),
            expect: true,
            body_has: Some("Plan 183"),
            body_lacks: None,
        },
        Row {
            name: "row_184",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "",
            title: None,
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_185",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-185",
            title: Some("   "),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_186",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-186",
            title: Some("password=pw186"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw186"),
        },
        Row {
            name: "row_187",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-187",
            title: Some("Thread 187"),
            err: Some("access_token=at187"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("at187"),
        },
        Row {
            name: "row_188",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-188",
            title: Some("secret=s188"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("s188"),
        },
        Row {
            name: "row_189",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-189",
            title: Some("api_key=extra-secret-189"),
            err: Some("token=extra-token-189"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-189"),
        },
        Row {
            name: "row_190",
            enabled: false,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-190",
            title: Some("Plan 190"),
            err: None,
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_191",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-191",
            title: None,
            err: Some("Bearer sk-extra191"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("sk-extra191"),
        },
        Row {
            name: "row_192",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-192",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_193",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-193",
            title: Some("password=pw193"),
            err: Some("key=k193"),
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("pw193"),
        },
        Row {
            name: "row_194",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-194",
            title: Some("Thread 194"),
            err: None,
            expect: true,
            body_has: Some("Thread 194"),
            body_lacks: None,
        },
        Row {
            name: "row_195",
            enabled: false,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-195",
            title: Some("secret=s195"),
            err: Some("plain error 195"),
            expect: false,
            body_has: None,
            body_lacks: None,
        },
        Row {
            name: "row_196",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-196",
            title: Some("api_key=extra-secret-196"),
            err: None,
            expect: true,
            body_has: Some(AMBIENT_REDACTED),
            body_lacks: Some("extra-secret-196"),
        },
        Row {
            name: "row_197",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-197",
            title: Some("Plan 197"),
            err: Some("timeout 197"),
            expect: true,
            body_has: Some("Plan 197"),
            body_lacks: None,
        },
        Row {
            name: "row_198",
            enabled: true,
            kind: GenerationNotifyKind::Completed,
            thread_id: "row-198",
            title: None,
            err: None,
            expect: true,
            body_has: Some("Finished generating"),
            body_lacks: None,
        },
        Row {
            name: "row_199",
            enabled: true,
            kind: GenerationNotifyKind::Failed,
            thread_id: "row-199",
            title: Some("   "),
            err: None,
            expect: true,
            body_has: Some("Generation failed"),
            body_lacks: None,
        },
    ];
    for row in rows {
        let shaped = shape_generation_notification(
            &NotificationPrefs {
                enabled: row.enabled,
            },
            &GenerationNotifyInput {
                kind: row.kind,
                thread_id: row.thread_id.into(),
                thread_title: row.title.map(str::to_string),
                error_summary: row.err.map(str::to_string),
            },
        );
        assert_eq!(shaped.is_some(), row.expect, "{}", row.name);
        if let Some(req) = shaped {
            assert_eq!(req.kind, row.kind, "{}", row.name);
            assert_eq!(
                req.default_action.as_deref(),
                Some(FOCUS_THREAD_ACTION),
                "{}",
                row.name
            );
            if let Some(frag) = row.body_has {
                assert!(
                    req.body.contains(frag),
                    "{} missing {:?} in {}",
                    row.name,
                    frag,
                    req.body
                );
            }
            if let Some(frag) = row.body_lacks {
                assert!(
                    !req.body.contains(frag),
                    "{} has leak {:?} in {}",
                    row.name,
                    frag,
                    req.body
                );
            }
        }
    }
}
