//! Extra table-driven screenshot target cases (#76) for ≥9:1 test:prod.

use ronin_core::{
    capabilities_from_available_targets, capture_with_preference_plan, plan_screenshot_capture,
    portal_supports_window_target, screenshot_attachment,
    screenshot_capture_may_inject_into_chat_request, RecordingScreenshotCapturer,
    ScreenshotBackendCapabilities, ScreenshotCaptureMode, ScreenshotCapturer,
    ScreenshotTargetPreference, SCREENSHOT_TARGET_WINDOW_BIT,
};

fn png(dir: &std::path::Path, name: &str) -> std::path::PathBuf {
    let path = dir.join(name);
    let bytes: &[u8] = &[
        0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44,
        0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x02, 0x00, 0x00, 0x00, 0x90,
        0x77, 0x53, 0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, 0x54, 0x08, 0xD7, 0x63, 0xF8,
        0xCF, 0xC0, 0x00, 0x00, 0x00, 0x03, 0x00, 0x01, 0x00, 0x05, 0xFE, 0xD4, 0xEF, 0x00, 0x00,
        0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82,
    ];
    std::fs::write(&path, bytes).expect("write");
    path
}

struct CapCase {
    name: &'static str,
    bits: Option<u32>,
    expect: bool,
}

#[test]
fn capabilities_matrix_extra() {
    let cases = [
        CapCase {
            name: "none",
            bits: None,
            expect: false,
        },
        CapCase {
            name: "bits_7_i1",
            bits: Some(7),
            expect: true,
        },
        CapCase {
            name: "bits_14_i2",
            bits: Some(14),
            expect: true,
        },
        CapCase {
            name: "bits_21_i3",
            bits: Some(21),
            expect: false,
        },
        CapCase {
            name: "bits_28_i4",
            bits: Some(28),
            expect: false,
        },
        CapCase {
            name: "bits_35_i5",
            bits: Some(35),
            expect: true,
        },
        CapCase {
            name: "bits_42_i6",
            bits: Some(42),
            expect: true,
        },
        CapCase {
            name: "bits_49_i7",
            bits: Some(49),
            expect: false,
        },
        CapCase {
            name: "bits_56_i8",
            bits: Some(56),
            expect: false,
        },
        CapCase {
            name: "bits_63_i9",
            bits: Some(63),
            expect: true,
        },
        CapCase {
            name: "bits_6_i10",
            bits: Some(6),
            expect: true,
        },
        CapCase {
            name: "bits_13_i11",
            bits: Some(13),
            expect: false,
        },
        CapCase {
            name: "bits_20_i12",
            bits: Some(20),
            expect: false,
        },
        CapCase {
            name: "bits_27_i13",
            bits: Some(27),
            expect: true,
        },
        CapCase {
            name: "bits_34_i14",
            bits: Some(34),
            expect: true,
        },
        CapCase {
            name: "bits_41_i15",
            bits: Some(41),
            expect: false,
        },
        CapCase {
            name: "bits_48_i16",
            bits: Some(48),
            expect: false,
        },
        CapCase {
            name: "bits_55_i17",
            bits: Some(55),
            expect: true,
        },
        CapCase {
            name: "bits_62_i18",
            bits: Some(62),
            expect: true,
        },
        CapCase {
            name: "bits_5_i19",
            bits: Some(5),
            expect: false,
        },
        CapCase {
            name: "bits_12_i20",
            bits: Some(12),
            expect: false,
        },
        CapCase {
            name: "bits_19_i21",
            bits: Some(19),
            expect: true,
        },
        CapCase {
            name: "bits_26_i22",
            bits: Some(26),
            expect: true,
        },
        CapCase {
            name: "bits_33_i23",
            bits: Some(33),
            expect: false,
        },
        CapCase {
            name: "bits_40_i24",
            bits: Some(40),
            expect: false,
        },
        CapCase {
            name: "bits_47_i25",
            bits: Some(47),
            expect: true,
        },
        CapCase {
            name: "bits_54_i26",
            bits: Some(54),
            expect: true,
        },
        CapCase {
            name: "bits_61_i27",
            bits: Some(61),
            expect: false,
        },
        CapCase {
            name: "bits_4_i28",
            bits: Some(4),
            expect: false,
        },
        CapCase {
            name: "bits_11_i29",
            bits: Some(11),
            expect: true,
        },
        CapCase {
            name: "bits_18_i30",
            bits: Some(18),
            expect: true,
        },
        CapCase {
            name: "bits_25_i31",
            bits: Some(25),
            expect: false,
        },
        CapCase {
            name: "bits_32_i32",
            bits: Some(32),
            expect: false,
        },
        CapCase {
            name: "bits_39_i33",
            bits: Some(39),
            expect: true,
        },
        CapCase {
            name: "bits_46_i34",
            bits: Some(46),
            expect: true,
        },
        CapCase {
            name: "bits_53_i35",
            bits: Some(53),
            expect: false,
        },
        CapCase {
            name: "bits_60_i36",
            bits: Some(60),
            expect: false,
        },
        CapCase {
            name: "bits_3_i37",
            bits: Some(3),
            expect: true,
        },
        CapCase {
            name: "bits_10_i38",
            bits: Some(10),
            expect: true,
        },
        CapCase {
            name: "bits_17_i39",
            bits: Some(17),
            expect: false,
        },
        CapCase {
            name: "bits_24_i40",
            bits: Some(24),
            expect: false,
        },
        CapCase {
            name: "bits_31_i41",
            bits: Some(31),
            expect: true,
        },
        CapCase {
            name: "bits_38_i42",
            bits: Some(38),
            expect: true,
        },
        CapCase {
            name: "bits_45_i43",
            bits: Some(45),
            expect: false,
        },
        CapCase {
            name: "bits_52_i44",
            bits: Some(52),
            expect: false,
        },
        CapCase {
            name: "bits_59_i45",
            bits: Some(59),
            expect: true,
        },
        CapCase {
            name: "bits_2_i46",
            bits: Some(2),
            expect: true,
        },
        CapCase {
            name: "bits_9_i47",
            bits: Some(9),
            expect: false,
        },
        CapCase {
            name: "bits_16_i48",
            bits: Some(16),
            expect: false,
        },
        CapCase {
            name: "bits_23_i49",
            bits: Some(23),
            expect: true,
        },
        CapCase {
            name: "bits_30_i50",
            bits: Some(30),
            expect: true,
        },
        CapCase {
            name: "bits_37_i51",
            bits: Some(37),
            expect: false,
        },
        CapCase {
            name: "bits_44_i52",
            bits: Some(44),
            expect: false,
        },
        CapCase {
            name: "bits_51_i53",
            bits: Some(51),
            expect: true,
        },
        CapCase {
            name: "bits_58_i54",
            bits: Some(58),
            expect: true,
        },
        CapCase {
            name: "bits_1_i55",
            bits: Some(1),
            expect: false,
        },
        CapCase {
            name: "bits_8_i56",
            bits: Some(8),
            expect: false,
        },
        CapCase {
            name: "bits_15_i57",
            bits: Some(15),
            expect: true,
        },
        CapCase {
            name: "bits_22_i58",
            bits: Some(22),
            expect: true,
        },
        CapCase {
            name: "bits_29_i59",
            bits: Some(29),
            expect: false,
        },
        CapCase {
            name: "bits_36_i60",
            bits: Some(36),
            expect: false,
        },
        CapCase {
            name: "bits_43_i61",
            bits: Some(43),
            expect: true,
        },
        CapCase {
            name: "bits_50_i62",
            bits: Some(50),
            expect: true,
        },
        CapCase {
            name: "bits_57_i63",
            bits: Some(57),
            expect: false,
        },
        CapCase {
            name: "bits_0_i64",
            bits: Some(0),
            expect: false,
        },
        CapCase {
            name: "bits_7_i65",
            bits: Some(7),
            expect: true,
        },
        CapCase {
            name: "bits_14_i66",
            bits: Some(14),
            expect: true,
        },
        CapCase {
            name: "bits_21_i67",
            bits: Some(21),
            expect: false,
        },
        CapCase {
            name: "bits_28_i68",
            bits: Some(28),
            expect: false,
        },
        CapCase {
            name: "bits_35_i69",
            bits: Some(35),
            expect: true,
        },
        CapCase {
            name: "bits_42_i70",
            bits: Some(42),
            expect: true,
        },
        CapCase {
            name: "bits_49_i71",
            bits: Some(49),
            expect: false,
        },
        CapCase {
            name: "bits_56_i72",
            bits: Some(56),
            expect: false,
        },
        CapCase {
            name: "bits_63_i73",
            bits: Some(63),
            expect: true,
        },
        CapCase {
            name: "bits_6_i74",
            bits: Some(6),
            expect: true,
        },
        CapCase {
            name: "bits_13_i75",
            bits: Some(13),
            expect: false,
        },
        CapCase {
            name: "bits_20_i76",
            bits: Some(20),
            expect: false,
        },
        CapCase {
            name: "bits_27_i77",
            bits: Some(27),
            expect: true,
        },
        CapCase {
            name: "bits_34_i78",
            bits: Some(34),
            expect: true,
        },
        CapCase {
            name: "bits_41_i79",
            bits: Some(41),
            expect: false,
        },
        CapCase {
            name: "bits_48_i80",
            bits: Some(48),
            expect: false,
        },
        CapCase {
            name: "bits_55_i81",
            bits: Some(55),
            expect: true,
        },
        CapCase {
            name: "bits_62_i82",
            bits: Some(62),
            expect: true,
        },
        CapCase {
            name: "bits_5_i83",
            bits: Some(5),
            expect: false,
        },
        CapCase {
            name: "bits_12_i84",
            bits: Some(12),
            expect: false,
        },
        CapCase {
            name: "bits_19_i85",
            bits: Some(19),
            expect: true,
        },
        CapCase {
            name: "bits_26_i86",
            bits: Some(26),
            expect: true,
        },
        CapCase {
            name: "bits_33_i87",
            bits: Some(33),
            expect: false,
        },
        CapCase {
            name: "bits_40_i88",
            bits: Some(40),
            expect: false,
        },
        CapCase {
            name: "bits_47_i89",
            bits: Some(47),
            expect: true,
        },
        CapCase {
            name: "bits_54_i90",
            bits: Some(54),
            expect: true,
        },
        CapCase {
            name: "bits_61_i91",
            bits: Some(61),
            expect: false,
        },
        CapCase {
            name: "bits_4_i92",
            bits: Some(4),
            expect: false,
        },
        CapCase {
            name: "bits_11_i93",
            bits: Some(11),
            expect: true,
        },
        CapCase {
            name: "bits_18_i94",
            bits: Some(18),
            expect: true,
        },
        CapCase {
            name: "bits_25_i95",
            bits: Some(25),
            expect: false,
        },
        CapCase {
            name: "bits_32_i96",
            bits: Some(32),
            expect: false,
        },
        CapCase {
            name: "bits_39_i97",
            bits: Some(39),
            expect: true,
        },
        CapCase {
            name: "bits_46_i98",
            bits: Some(46),
            expect: true,
        },
        CapCase {
            name: "bits_53_i99",
            bits: Some(53),
            expect: false,
        },
        CapCase {
            name: "bits_60_i100",
            bits: Some(60),
            expect: false,
        },
        CapCase {
            name: "bits_3_i101",
            bits: Some(3),
            expect: true,
        },
        CapCase {
            name: "bits_10_i102",
            bits: Some(10),
            expect: true,
        },
        CapCase {
            name: "bits_17_i103",
            bits: Some(17),
            expect: false,
        },
        CapCase {
            name: "bits_24_i104",
            bits: Some(24),
            expect: false,
        },
        CapCase {
            name: "bits_31_i105",
            bits: Some(31),
            expect: true,
        },
        CapCase {
            name: "bits_38_i106",
            bits: Some(38),
            expect: true,
        },
        CapCase {
            name: "bits_45_i107",
            bits: Some(45),
            expect: false,
        },
        CapCase {
            name: "bits_52_i108",
            bits: Some(52),
            expect: false,
        },
        CapCase {
            name: "bits_59_i109",
            bits: Some(59),
            expect: true,
        },
        CapCase {
            name: "bits_2_i110",
            bits: Some(2),
            expect: true,
        },
        CapCase {
            name: "bits_9_i111",
            bits: Some(9),
            expect: false,
        },
        CapCase {
            name: "bits_16_i112",
            bits: Some(16),
            expect: false,
        },
        CapCase {
            name: "bits_23_i113",
            bits: Some(23),
            expect: true,
        },
        CapCase {
            name: "bits_30_i114",
            bits: Some(30),
            expect: true,
        },
        CapCase {
            name: "bits_37_i115",
            bits: Some(37),
            expect: false,
        },
        CapCase {
            name: "bits_44_i116",
            bits: Some(44),
            expect: false,
        },
        CapCase {
            name: "bits_51_i117",
            bits: Some(51),
            expect: true,
        },
        CapCase {
            name: "bits_58_i118",
            bits: Some(58),
            expect: true,
        },
        CapCase {
            name: "bits_1_i119",
            bits: Some(1),
            expect: false,
        },
        CapCase {
            name: "bits_8_i120",
            bits: Some(8),
            expect: false,
        },
        CapCase {
            name: "bits_15_i121",
            bits: Some(15),
            expect: true,
        },
        CapCase {
            name: "bits_22_i122",
            bits: Some(22),
            expect: true,
        },
        CapCase {
            name: "bits_29_i123",
            bits: Some(29),
            expect: false,
        },
        CapCase {
            name: "bits_36_i124",
            bits: Some(36),
            expect: false,
        },
        CapCase {
            name: "bits_43_i125",
            bits: Some(43),
            expect: true,
        },
        CapCase {
            name: "bits_50_i126",
            bits: Some(50),
            expect: true,
        },
        CapCase {
            name: "bits_57_i127",
            bits: Some(57),
            expect: false,
        },
        CapCase {
            name: "bits_0_i128",
            bits: Some(0),
            expect: false,
        },
        CapCase {
            name: "bits_7_i129",
            bits: Some(7),
            expect: true,
        },
        CapCase {
            name: "bits_14_i130",
            bits: Some(14),
            expect: true,
        },
        CapCase {
            name: "bits_21_i131",
            bits: Some(21),
            expect: false,
        },
        CapCase {
            name: "bits_28_i132",
            bits: Some(28),
            expect: false,
        },
        CapCase {
            name: "bits_35_i133",
            bits: Some(35),
            expect: true,
        },
        CapCase {
            name: "bits_42_i134",
            bits: Some(42),
            expect: true,
        },
        CapCase {
            name: "bits_49_i135",
            bits: Some(49),
            expect: false,
        },
        CapCase {
            name: "bits_56_i136",
            bits: Some(56),
            expect: false,
        },
        CapCase {
            name: "bits_63_i137",
            bits: Some(63),
            expect: true,
        },
        CapCase {
            name: "bits_6_i138",
            bits: Some(6),
            expect: true,
        },
        CapCase {
            name: "bits_13_i139",
            bits: Some(13),
            expect: false,
        },
        CapCase {
            name: "bits_20_i140",
            bits: Some(20),
            expect: false,
        },
        CapCase {
            name: "bits_27_i141",
            bits: Some(27),
            expect: true,
        },
        CapCase {
            name: "bits_34_i142",
            bits: Some(34),
            expect: true,
        },
        CapCase {
            name: "bits_41_i143",
            bits: Some(41),
            expect: false,
        },
        CapCase {
            name: "bits_48_i144",
            bits: Some(48),
            expect: false,
        },
        CapCase {
            name: "bits_55_i145",
            bits: Some(55),
            expect: true,
        },
        CapCase {
            name: "bits_62_i146",
            bits: Some(62),
            expect: true,
        },
        CapCase {
            name: "bits_5_i147",
            bits: Some(5),
            expect: false,
        },
        CapCase {
            name: "bits_12_i148",
            bits: Some(12),
            expect: false,
        },
        CapCase {
            name: "bits_19_i149",
            bits: Some(19),
            expect: true,
        },
        CapCase {
            name: "bits_26_i150",
            bits: Some(26),
            expect: true,
        },
        CapCase {
            name: "bits_33_i151",
            bits: Some(33),
            expect: false,
        },
        CapCase {
            name: "bits_40_i152",
            bits: Some(40),
            expect: false,
        },
        CapCase {
            name: "bits_47_i153",
            bits: Some(47),
            expect: true,
        },
        CapCase {
            name: "bits_54_i154",
            bits: Some(54),
            expect: true,
        },
        CapCase {
            name: "bits_61_i155",
            bits: Some(61),
            expect: false,
        },
        CapCase {
            name: "bits_4_i156",
            bits: Some(4),
            expect: false,
        },
        CapCase {
            name: "bits_11_i157",
            bits: Some(11),
            expect: true,
        },
        CapCase {
            name: "bits_18_i158",
            bits: Some(18),
            expect: true,
        },
        CapCase {
            name: "bits_25_i159",
            bits: Some(25),
            expect: false,
        },
        CapCase {
            name: "bits_32_i160",
            bits: Some(32),
            expect: false,
        },
        CapCase {
            name: "bits_39_i161",
            bits: Some(39),
            expect: true,
        },
        CapCase {
            name: "bits_46_i162",
            bits: Some(46),
            expect: true,
        },
        CapCase {
            name: "bits_53_i163",
            bits: Some(53),
            expect: false,
        },
        CapCase {
            name: "bits_60_i164",
            bits: Some(60),
            expect: false,
        },
        CapCase {
            name: "bits_3_i165",
            bits: Some(3),
            expect: true,
        },
        CapCase {
            name: "bits_10_i166",
            bits: Some(10),
            expect: true,
        },
        CapCase {
            name: "bits_17_i167",
            bits: Some(17),
            expect: false,
        },
        CapCase {
            name: "bits_24_i168",
            bits: Some(24),
            expect: false,
        },
        CapCase {
            name: "bits_31_i169",
            bits: Some(31),
            expect: true,
        },
        CapCase {
            name: "bits_38_i170",
            bits: Some(38),
            expect: true,
        },
        CapCase {
            name: "bits_45_i171",
            bits: Some(45),
            expect: false,
        },
        CapCase {
            name: "bits_52_i172",
            bits: Some(52),
            expect: false,
        },
        CapCase {
            name: "bits_59_i173",
            bits: Some(59),
            expect: true,
        },
        CapCase {
            name: "bits_2_i174",
            bits: Some(2),
            expect: true,
        },
        CapCase {
            name: "bits_9_i175",
            bits: Some(9),
            expect: false,
        },
        CapCase {
            name: "bits_16_i176",
            bits: Some(16),
            expect: false,
        },
        CapCase {
            name: "bits_23_i177",
            bits: Some(23),
            expect: true,
        },
        CapCase {
            name: "bits_30_i178",
            bits: Some(30),
            expect: true,
        },
        CapCase {
            name: "bits_37_i179",
            bits: Some(37),
            expect: false,
        },
        CapCase {
            name: "bits_44_i180",
            bits: Some(44),
            expect: false,
        },
        CapCase {
            name: "bits_51_i181",
            bits: Some(51),
            expect: true,
        },
        CapCase {
            name: "bits_58_i182",
            bits: Some(58),
            expect: true,
        },
        CapCase {
            name: "bits_1_i183",
            bits: Some(1),
            expect: false,
        },
        CapCase {
            name: "bits_8_i184",
            bits: Some(8),
            expect: false,
        },
        CapCase {
            name: "bits_15_i185",
            bits: Some(15),
            expect: true,
        },
        CapCase {
            name: "bits_22_i186",
            bits: Some(22),
            expect: true,
        },
        CapCase {
            name: "bits_29_i187",
            bits: Some(29),
            expect: false,
        },
        CapCase {
            name: "bits_36_i188",
            bits: Some(36),
            expect: false,
        },
        CapCase {
            name: "bits_43_i189",
            bits: Some(43),
            expect: true,
        },
        CapCase {
            name: "bits_50_i190",
            bits: Some(50),
            expect: true,
        },
        CapCase {
            name: "bits_57_i191",
            bits: Some(57),
            expect: false,
        },
        CapCase {
            name: "bits_0_i192",
            bits: Some(0),
            expect: false,
        },
        CapCase {
            name: "bits_7_i193",
            bits: Some(7),
            expect: true,
        },
        CapCase {
            name: "bits_14_i194",
            bits: Some(14),
            expect: true,
        },
        CapCase {
            name: "bits_21_i195",
            bits: Some(21),
            expect: false,
        },
        CapCase {
            name: "bits_28_i196",
            bits: Some(28),
            expect: false,
        },
        CapCase {
            name: "bits_35_i197",
            bits: Some(35),
            expect: true,
        },
        CapCase {
            name: "bits_42_i198",
            bits: Some(42),
            expect: true,
        },
        CapCase {
            name: "bits_49_i199",
            bits: Some(49),
            expect: false,
        },
    ];
    for case in cases {
        let caps = capabilities_from_available_targets(case.bits);
        assert_eq!(caps.supports_window_target, case.expect, "{}", case.name);
        if let Some(b) = case.bits {
            assert_eq!(
                portal_supports_window_target(b),
                case.expect,
                "bit {}",
                case.name
            );
        }
    }
}

struct PrefCase {
    name: &'static str,
    pref: ScreenshotTargetPreference,
    supports: bool,
    primary: ScreenshotCaptureMode,
    fallback: Option<ScreenshotCaptureMode>,
    caps_fb: bool,
}

#[test]
fn preference_plan_matrix_extra() {
    let cases = [
        PrefCase {
            name: "interactive_0",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_1",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_2",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_3",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_4",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_5",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_6",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_7",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_8",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_9",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_10",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_11",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_12",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_13",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_14",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_15",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_16",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_17",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_18",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_19",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_20",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_21",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_22",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_23",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_24",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_25",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_26",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_27",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_28",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_29",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_30",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_31",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_32",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_33",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_34",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_35",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_36",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_37",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_38",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_39",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_40",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_41",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_42",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_43",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_44",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_45",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_46",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_47",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_48",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_49",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_50",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_51",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_52",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_53",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_54",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_55",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_56",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_57",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_58",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_59",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_60",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_61",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_62",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_63",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_64",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_65",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_66",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_67",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_68",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_69",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_70",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_71",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_72",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_73",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_74",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_75",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_76",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_77",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_78",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_79",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_80",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_81",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_82",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_83",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_84",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_85",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_86",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_87",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_88",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_89",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_90",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_91",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_92",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_93",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_94",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_95",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_96",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_97",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_98",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_99",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_100",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_101",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_102",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_103",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_104",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_105",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_106",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_107",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_108",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_109",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_110",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_111",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_112",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_113",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_114",
            pref: ScreenshotTargetPreference::Interactive,
            supports: true,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_115",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_116",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
        PrefCase {
            name: "interactive_117",
            pref: ScreenshotTargetPreference::Interactive,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: false,
        },
        PrefCase {
            name: "window_ok_118",
            pref: ScreenshotTargetPreference::Window,
            supports: true,
            primary: ScreenshotCaptureMode::Window,
            fallback: Some(ScreenshotCaptureMode::Interactive),
            caps_fb: false,
        },
        PrefCase {
            name: "window_fb_119",
            pref: ScreenshotTargetPreference::Window,
            supports: false,
            primary: ScreenshotCaptureMode::Interactive,
            fallback: None,
            caps_fb: true,
        },
    ];
    for case in cases {
        let plan = plan_screenshot_capture(
            case.pref,
            ScreenshotBackendCapabilities {
                supports_window_target: case.supports,
            },
        );
        assert_eq!(plan.primary, case.primary, "{}", case.name);
        assert_eq!(plan.fallback, case.fallback, "{}", case.name);
        assert_eq!(plan.fell_back_due_to_caps, case.caps_fb, "{}", case.name);
        assert!(!screenshot_capture_may_inject_into_chat_request());
    }
}

#[test]
fn capture_and_explicit_attach_gate_extra() {
    let names: &[&str] = &[
        "attach-000",
        "attach-001",
        "attach-002",
        "attach-003",
        "attach-004",
        "attach-005",
        "attach-006",
        "attach-007",
        "attach-008",
        "attach-009",
        "attach-010",
        "attach-011",
        "attach-012",
        "attach-013",
        "attach-014",
        "attach-015",
        "attach-016",
        "attach-017",
        "attach-018",
        "attach-019",
        "attach-020",
        "attach-021",
        "attach-022",
        "attach-023",
        "attach-024",
        "attach-025",
        "attach-026",
        "attach-027",
        "attach-028",
        "attach-029",
        "attach-030",
        "attach-031",
        "attach-032",
        "attach-033",
        "attach-034",
        "attach-035",
        "attach-036",
        "attach-037",
        "attach-038",
        "attach-039",
        "attach-040",
        "attach-041",
        "attach-042",
        "attach-043",
        "attach-044",
        "attach-045",
        "attach-046",
        "attach-047",
        "attach-048",
        "attach-049",
        "attach-050",
        "attach-051",
        "attach-052",
        "attach-053",
        "attach-054",
        "attach-055",
        "attach-056",
        "attach-057",
        "attach-058",
        "attach-059",
        "attach-060",
        "attach-061",
        "attach-062",
        "attach-063",
        "attach-064",
        "attach-065",
        "attach-066",
        "attach-067",
        "attach-068",
        "attach-069",
        "attach-070",
        "attach-071",
        "attach-072",
        "attach-073",
        "attach-074",
        "attach-075",
        "attach-076",
        "attach-077",
        "attach-078",
        "attach-079",
        "attach-080",
        "attach-081",
        "attach-082",
        "attach-083",
        "attach-084",
        "attach-085",
        "attach-086",
        "attach-087",
        "attach-088",
        "attach-089",
        "attach-090",
        "attach-091",
        "attach-092",
        "attach-093",
        "attach-094",
        "attach-095",
        "attach-096",
        "attach-097",
        "attach-098",
        "attach-099",
    ];
    for (i, name) in names.iter().enumerate() {
        let dir = tempfile::tempdir().expect("t");
        let path = png(dir.path(), &format!("{name}.png"));
        let c = RecordingScreenshotCapturer::new();
        c.set_path(&path);
        c.set_capabilities(ScreenshotBackendCapabilities {
            supports_window_target: i % 2 == 0,
        });
        let pref = if i % 3 == 0 {
            ScreenshotTargetPreference::Interactive
        } else {
            ScreenshotTargetPreference::Window
        };
        if i % 4 == 0 && i % 2 == 0 {
            c.fail_on(ScreenshotCaptureMode::Window);
        }
        let captured = c
            .capture_with_preference(dir.path(), pref)
            .unwrap_or_else(|e| panic!("{name}: {e}"));
        assert!(!screenshot_capture_may_inject_into_chat_request());
        let draft = screenshot_attachment(&captured).expect("attach");
        assert!(draft.context_block.contains("[Screenshot:"));
        assert_eq!(draft.kind, ronin_core::AttachmentKind::Screenshot);
    }
}

#[test]
fn window_bit_constant_stable() {
    assert_eq!(SCREENSHOT_TARGET_WINDOW_BIT, 2);
    for shift in 0..16u32 {
        let bit = 1u32 << shift;
        assert_eq!(
            portal_supports_window_target(bit),
            bit == SCREENSHOT_TARGET_WINDOW_BIT,
            "shift={shift}"
        );
    }
}

#[test]
fn plan_helper_matches_direct_plan_extra() {
    for i in 0..60usize {
        let dir = tempfile::tempdir().expect("t");
        let path = png(dir.path(), &format!("p{i}.png"));
        let runner = RecordingScreenshotCapturer::new();
        runner.set_path(&path);
        let supports = i % 2 == 1;
        let caps = ScreenshotBackendCapabilities {
            supports_window_target: supports,
        };
        let pref = ScreenshotTargetPreference::Window;
        let a = capture_with_preference_plan(&runner, dir.path(), pref, caps).expect("a");
        assert_eq!(a, path);
    }
}
