//! Table-driven public-seam resolve cases for thread workspace root (#70).
//!
//! Covers relative-vs-absolute resolution matrices at `resolve_context_path` /
//! `context_path_base` without probing the filesystem for git/CWD auto-bind.

use std::path::{Path, PathBuf};

use ronin_core::{context_path_base, resolve_context_path};

type RelCase = (&'static str, &'static str, &'static str);

fn relative_with_workspace_cases() -> Vec<RelCase> {
    vec![
        ("/ws", "a.rs", "/ws/a.rs"),
        ("/ws", "src/main.rs", "/ws/src/main.rs"),
        ("/ws", "docs/readme.md", "/ws/docs/readme.md"),
        ("/ws", "lib/mod.rs", "/ws/lib/mod.rs"),
        ("/ws", "Cargo.toml", "/ws/Cargo.toml"),
        ("/ws", "nested/deep/file.txt", "/ws/nested/deep/file.txt"),
        ("/ws", "./rel.txt", "/ws/./rel.txt"),
        ("/ws", "cfg/app.toml", "/ws/cfg/app.toml"),
        ("/ws", "pkg/foo/bar.rs", "/ws/pkg/foo/bar.rs"),
        ("/ws", "folder", "/ws/folder"),
        ("/ws", "../outer.txt", "/ws/../outer.txt"),
        (
            "/ws",
            "tests/workspace_root.rs",
            "/ws/tests/workspace_root.rs",
        ),
        (
            "/ws",
            "crates/ronin_core/src/lib.rs",
            "/ws/crates/ronin_core/src/lib.rs",
        ),
        ("/ws", "apps/web/index.html", "/ws/apps/web/index.html"),
        ("/ws", "README", "/ws/README"),
        ("/ws", "x", "/ws/x"),
        ("/ws", "x/y", "/ws/x/y"),
        ("/ws", "x/y/z", "/ws/x/y/z"),
        ("/ws", ".env.example", "/ws/.env.example"),
        (
            "/ws",
            ".github/workflows/ci.yml",
            "/ws/.github/workflows/ci.yml",
        ),
        ("/ws", "src/bin/cli.rs", "/ws/src/bin/cli.rs"),
        ("/ws", "scripts/setup.sh", "/ws/scripts/setup.sh"),
        ("/ws", "docs/standards.md", "/ws/docs/standards.md"),
        ("/ws", "loop/PRD.md", "/ws/loop/PRD.md"),
        (
            "/ws",
            "fixtures/with spaces.txt",
            "/ws/fixtures/with spaces.txt",
        ),
        ("/ws", "Makefile", "/ws/Makefile"),
        ("/ws", "build.rs", "/ws/build.rs"),
        ("/ws", "src/context.rs", "/ws/src/context.rs"),
        (
            "/ws",
            "crates/ronin_db/src/lib.rs",
            "/ws/crates/ronin_db/src/lib.rs",
        ),
        (
            "/ws",
            "crates/ronin_app/src/shell.rs",
            "/ws/crates/ronin_app/src/shell.rs",
        ),
        ("/home/u/proj", "a.rs", "/home/u/proj/a.rs"),
        ("/home/u/proj", "src/main.rs", "/home/u/proj/src/main.rs"),
        (
            "/home/u/proj",
            "docs/readme.md",
            "/home/u/proj/docs/readme.md",
        ),
        ("/home/u/proj", "lib/mod.rs", "/home/u/proj/lib/mod.rs"),
        ("/home/u/proj", "Cargo.toml", "/home/u/proj/Cargo.toml"),
        (
            "/home/u/proj",
            "nested/deep/file.txt",
            "/home/u/proj/nested/deep/file.txt",
        ),
        ("/home/u/proj", "./rel.txt", "/home/u/proj/./rel.txt"),
        ("/home/u/proj", "cfg/app.toml", "/home/u/proj/cfg/app.toml"),
        (
            "/home/u/proj",
            "pkg/foo/bar.rs",
            "/home/u/proj/pkg/foo/bar.rs",
        ),
        ("/home/u/proj", "folder", "/home/u/proj/folder"),
        ("/home/u/proj", "../outer.txt", "/home/u/proj/../outer.txt"),
        (
            "/home/u/proj",
            "tests/workspace_root.rs",
            "/home/u/proj/tests/workspace_root.rs",
        ),
        (
            "/home/u/proj",
            "crates/ronin_core/src/lib.rs",
            "/home/u/proj/crates/ronin_core/src/lib.rs",
        ),
        (
            "/home/u/proj",
            "apps/web/index.html",
            "/home/u/proj/apps/web/index.html",
        ),
        ("/home/u/proj", "README", "/home/u/proj/README"),
        ("/home/u/proj", "x", "/home/u/proj/x"),
        ("/home/u/proj", "x/y", "/home/u/proj/x/y"),
        ("/home/u/proj", "x/y/z", "/home/u/proj/x/y/z"),
        ("/home/u/proj", ".env.example", "/home/u/proj/.env.example"),
        (
            "/home/u/proj",
            ".github/workflows/ci.yml",
            "/home/u/proj/.github/workflows/ci.yml",
        ),
        (
            "/home/u/proj",
            "src/bin/cli.rs",
            "/home/u/proj/src/bin/cli.rs",
        ),
        (
            "/home/u/proj",
            "scripts/setup.sh",
            "/home/u/proj/scripts/setup.sh",
        ),
        (
            "/home/u/proj",
            "docs/standards.md",
            "/home/u/proj/docs/standards.md",
        ),
        ("/home/u/proj", "loop/PRD.md", "/home/u/proj/loop/PRD.md"),
        (
            "/home/u/proj",
            "fixtures/with spaces.txt",
            "/home/u/proj/fixtures/with spaces.txt",
        ),
        ("/home/u/proj", "Makefile", "/home/u/proj/Makefile"),
        ("/home/u/proj", "build.rs", "/home/u/proj/build.rs"),
        (
            "/home/u/proj",
            "src/context.rs",
            "/home/u/proj/src/context.rs",
        ),
        (
            "/home/u/proj",
            "crates/ronin_db/src/lib.rs",
            "/home/u/proj/crates/ronin_db/src/lib.rs",
        ),
        (
            "/home/u/proj",
            "crates/ronin_app/src/shell.rs",
            "/home/u/proj/crates/ronin_app/src/shell.rs",
        ),
        ("/tmp/root", "a.rs", "/tmp/root/a.rs"),
        ("/tmp/root", "src/main.rs", "/tmp/root/src/main.rs"),
        ("/tmp/root", "docs/readme.md", "/tmp/root/docs/readme.md"),
        ("/tmp/root", "lib/mod.rs", "/tmp/root/lib/mod.rs"),
        ("/tmp/root", "Cargo.toml", "/tmp/root/Cargo.toml"),
        (
            "/tmp/root",
            "nested/deep/file.txt",
            "/tmp/root/nested/deep/file.txt",
        ),
        ("/tmp/root", "./rel.txt", "/tmp/root/./rel.txt"),
        ("/tmp/root", "cfg/app.toml", "/tmp/root/cfg/app.toml"),
        ("/tmp/root", "pkg/foo/bar.rs", "/tmp/root/pkg/foo/bar.rs"),
        ("/tmp/root", "folder", "/tmp/root/folder"),
        ("/tmp/root", "../outer.txt", "/tmp/root/../outer.txt"),
        (
            "/tmp/root",
            "tests/workspace_root.rs",
            "/tmp/root/tests/workspace_root.rs",
        ),
        (
            "/tmp/root",
            "crates/ronin_core/src/lib.rs",
            "/tmp/root/crates/ronin_core/src/lib.rs",
        ),
        (
            "/tmp/root",
            "apps/web/index.html",
            "/tmp/root/apps/web/index.html",
        ),
        ("/tmp/root", "README", "/tmp/root/README"),
        ("/tmp/root", "x", "/tmp/root/x"),
        ("/tmp/root", "x/y", "/tmp/root/x/y"),
        ("/tmp/root", "x/y/z", "/tmp/root/x/y/z"),
        ("/tmp/root", ".env.example", "/tmp/root/.env.example"),
        (
            "/tmp/root",
            ".github/workflows/ci.yml",
            "/tmp/root/.github/workflows/ci.yml",
        ),
        ("/tmp/root", "src/bin/cli.rs", "/tmp/root/src/bin/cli.rs"),
        (
            "/tmp/root",
            "scripts/setup.sh",
            "/tmp/root/scripts/setup.sh",
        ),
        (
            "/tmp/root",
            "docs/standards.md",
            "/tmp/root/docs/standards.md",
        ),
        ("/tmp/root", "loop/PRD.md", "/tmp/root/loop/PRD.md"),
        (
            "/tmp/root",
            "fixtures/with spaces.txt",
            "/tmp/root/fixtures/with spaces.txt",
        ),
        ("/tmp/root", "Makefile", "/tmp/root/Makefile"),
        ("/tmp/root", "build.rs", "/tmp/root/build.rs"),
        ("/tmp/root", "src/context.rs", "/tmp/root/src/context.rs"),
        (
            "/tmp/root",
            "crates/ronin_db/src/lib.rs",
            "/tmp/root/crates/ronin_db/src/lib.rs",
        ),
        (
            "/tmp/root",
            "crates/ronin_app/src/shell.rs",
            "/tmp/root/crates/ronin_app/src/shell.rs",
        ),
        ("/opt/app", "a.rs", "/opt/app/a.rs"),
        ("/opt/app", "src/main.rs", "/opt/app/src/main.rs"),
        ("/opt/app", "docs/readme.md", "/opt/app/docs/readme.md"),
        ("/opt/app", "lib/mod.rs", "/opt/app/lib/mod.rs"),
        ("/opt/app", "Cargo.toml", "/opt/app/Cargo.toml"),
        (
            "/opt/app",
            "nested/deep/file.txt",
            "/opt/app/nested/deep/file.txt",
        ),
        ("/opt/app", "./rel.txt", "/opt/app/./rel.txt"),
        ("/opt/app", "cfg/app.toml", "/opt/app/cfg/app.toml"),
        ("/opt/app", "pkg/foo/bar.rs", "/opt/app/pkg/foo/bar.rs"),
        ("/opt/app", "folder", "/opt/app/folder"),
        ("/opt/app", "../outer.txt", "/opt/app/../outer.txt"),
        (
            "/opt/app",
            "tests/workspace_root.rs",
            "/opt/app/tests/workspace_root.rs",
        ),
        (
            "/opt/app",
            "crates/ronin_core/src/lib.rs",
            "/opt/app/crates/ronin_core/src/lib.rs",
        ),
        (
            "/opt/app",
            "apps/web/index.html",
            "/opt/app/apps/web/index.html",
        ),
        ("/opt/app", "README", "/opt/app/README"),
        ("/opt/app", "x", "/opt/app/x"),
        ("/opt/app", "x/y", "/opt/app/x/y"),
        ("/opt/app", "x/y/z", "/opt/app/x/y/z"),
        ("/opt/app", ".env.example", "/opt/app/.env.example"),
        (
            "/opt/app",
            ".github/workflows/ci.yml",
            "/opt/app/.github/workflows/ci.yml",
        ),
        ("/opt/app", "src/bin/cli.rs", "/opt/app/src/bin/cli.rs"),
        ("/opt/app", "scripts/setup.sh", "/opt/app/scripts/setup.sh"),
        (
            "/opt/app",
            "docs/standards.md",
            "/opt/app/docs/standards.md",
        ),
        ("/opt/app", "loop/PRD.md", "/opt/app/loop/PRD.md"),
        (
            "/opt/app",
            "fixtures/with spaces.txt",
            "/opt/app/fixtures/with spaces.txt",
        ),
        ("/opt/app", "Makefile", "/opt/app/Makefile"),
        ("/opt/app", "build.rs", "/opt/app/build.rs"),
        ("/opt/app", "src/context.rs", "/opt/app/src/context.rs"),
        (
            "/opt/app",
            "crates/ronin_db/src/lib.rs",
            "/opt/app/crates/ronin_db/src/lib.rs",
        ),
        (
            "/opt/app",
            "crates/ronin_app/src/shell.rs",
            "/opt/app/crates/ronin_app/src/shell.rs",
        ),
        ("/srv/code", "a.rs", "/srv/code/a.rs"),
        ("/srv/code", "src/main.rs", "/srv/code/src/main.rs"),
        ("/srv/code", "docs/readme.md", "/srv/code/docs/readme.md"),
        ("/srv/code", "lib/mod.rs", "/srv/code/lib/mod.rs"),
        ("/srv/code", "Cargo.toml", "/srv/code/Cargo.toml"),
        (
            "/srv/code",
            "nested/deep/file.txt",
            "/srv/code/nested/deep/file.txt",
        ),
        ("/srv/code", "./rel.txt", "/srv/code/./rel.txt"),
        ("/srv/code", "cfg/app.toml", "/srv/code/cfg/app.toml"),
        ("/srv/code", "pkg/foo/bar.rs", "/srv/code/pkg/foo/bar.rs"),
        ("/srv/code", "folder", "/srv/code/folder"),
        ("/srv/code", "../outer.txt", "/srv/code/../outer.txt"),
        (
            "/srv/code",
            "tests/workspace_root.rs",
            "/srv/code/tests/workspace_root.rs",
        ),
        (
            "/srv/code",
            "crates/ronin_core/src/lib.rs",
            "/srv/code/crates/ronin_core/src/lib.rs",
        ),
        (
            "/srv/code",
            "apps/web/index.html",
            "/srv/code/apps/web/index.html",
        ),
        ("/srv/code", "README", "/srv/code/README"),
        ("/srv/code", "x", "/srv/code/x"),
        ("/srv/code", "x/y", "/srv/code/x/y"),
        ("/srv/code", "x/y/z", "/srv/code/x/y/z"),
        ("/srv/code", ".env.example", "/srv/code/.env.example"),
        (
            "/srv/code",
            ".github/workflows/ci.yml",
            "/srv/code/.github/workflows/ci.yml",
        ),
    ]
}

fn relative_without_workspace_cases() -> Vec<RelCase> {
    vec![
        ("/cwd", "a.rs", "/cwd/a.rs"),
        ("/cwd", "src/main.rs", "/cwd/src/main.rs"),
        ("/cwd", "notes.txt", "/cwd/notes.txt"),
        ("/cwd", "Downloads/file.md", "/cwd/Downloads/file.md"),
        ("/cwd", "local.txt", "/cwd/local.txt"),
        ("/cwd", "scratch.rs", "/cwd/scratch.rs"),
        ("/cwd", "nested/path/file", "/cwd/nested/path/file"),
        ("/cwd", "./dot.txt", "/cwd/./dot.txt"),
        ("/cwd", "dir", "/cwd/dir"),
        ("/cwd", "a/b/c/d", "/cwd/a/b/c/d"),
        ("/cwd", "only.txt", "/cwd/only.txt"),
        ("/cwd", "pkg/lib.rs", "/cwd/pkg/lib.rs"),
        ("/cwd", "x", "/cwd/x"),
        ("/cwd", "x/y", "/cwd/x/y"),
        ("/cwd", "x/y/z.md", "/cwd/x/y/z.md"),
        ("/cwd", "composer.txt", "/cwd/composer.txt"),
        ("/cwd", "attach/me.md", "/cwd/attach/me.md"),
        ("/cwd", "rel/path/to/file.rs", "/cwd/rel/path/to/file.rs"),
        ("/tmp", "a.rs", "/tmp/a.rs"),
        ("/tmp", "src/main.rs", "/tmp/src/main.rs"),
        ("/tmp", "notes.txt", "/tmp/notes.txt"),
        ("/tmp", "Downloads/file.md", "/tmp/Downloads/file.md"),
        ("/tmp", "local.txt", "/tmp/local.txt"),
        ("/tmp", "scratch.rs", "/tmp/scratch.rs"),
        ("/tmp", "nested/path/file", "/tmp/nested/path/file"),
        ("/tmp", "./dot.txt", "/tmp/./dot.txt"),
        ("/tmp", "dir", "/tmp/dir"),
        ("/tmp", "a/b/c/d", "/tmp/a/b/c/d"),
        ("/tmp", "only.txt", "/tmp/only.txt"),
        ("/tmp", "pkg/lib.rs", "/tmp/pkg/lib.rs"),
        ("/tmp", "x", "/tmp/x"),
        ("/tmp", "x/y", "/tmp/x/y"),
        ("/tmp", "x/y/z.md", "/tmp/x/y/z.md"),
        ("/tmp", "composer.txt", "/tmp/composer.txt"),
        ("/tmp", "attach/me.md", "/tmp/attach/me.md"),
        ("/tmp", "rel/path/to/file.rs", "/tmp/rel/path/to/file.rs"),
        ("/home/u", "a.rs", "/home/u/a.rs"),
        ("/home/u", "src/main.rs", "/home/u/src/main.rs"),
        ("/home/u", "notes.txt", "/home/u/notes.txt"),
        ("/home/u", "Downloads/file.md", "/home/u/Downloads/file.md"),
        ("/home/u", "local.txt", "/home/u/local.txt"),
        ("/home/u", "scratch.rs", "/home/u/scratch.rs"),
        ("/home/u", "nested/path/file", "/home/u/nested/path/file"),
        ("/home/u", "./dot.txt", "/home/u/./dot.txt"),
        ("/home/u", "dir", "/home/u/dir"),
        ("/home/u", "a/b/c/d", "/home/u/a/b/c/d"),
        ("/home/u", "only.txt", "/home/u/only.txt"),
        ("/home/u", "pkg/lib.rs", "/home/u/pkg/lib.rs"),
        ("/home/u", "x", "/home/u/x"),
        ("/home/u", "x/y", "/home/u/x/y"),
        ("/home/u", "x/y/z.md", "/home/u/x/y/z.md"),
        ("/home/u", "composer.txt", "/home/u/composer.txt"),
        ("/home/u", "attach/me.md", "/home/u/attach/me.md"),
        (
            "/home/u",
            "rel/path/to/file.rs",
            "/home/u/rel/path/to/file.rs",
        ),
        ("/var/tmp", "a.rs", "/var/tmp/a.rs"),
        ("/var/tmp", "src/main.rs", "/var/tmp/src/main.rs"),
        ("/var/tmp", "notes.txt", "/var/tmp/notes.txt"),
        (
            "/var/tmp",
            "Downloads/file.md",
            "/var/tmp/Downloads/file.md",
        ),
        ("/var/tmp", "local.txt", "/var/tmp/local.txt"),
        ("/var/tmp", "scratch.rs", "/var/tmp/scratch.rs"),
        ("/var/tmp", "nested/path/file", "/var/tmp/nested/path/file"),
        ("/var/tmp", "./dot.txt", "/var/tmp/./dot.txt"),
        ("/var/tmp", "dir", "/var/tmp/dir"),
        ("/var/tmp", "a/b/c/d", "/var/tmp/a/b/c/d"),
        ("/var/tmp", "only.txt", "/var/tmp/only.txt"),
        ("/var/tmp", "pkg/lib.rs", "/var/tmp/pkg/lib.rs"),
        ("/var/tmp", "x", "/var/tmp/x"),
        ("/var/tmp", "x/y", "/var/tmp/x/y"),
        ("/var/tmp", "x/y/z.md", "/var/tmp/x/y/z.md"),
        ("/var/tmp", "composer.txt", "/var/tmp/composer.txt"),
        ("/var/tmp", "attach/me.md", "/var/tmp/attach/me.md"),
        (
            "/var/tmp",
            "rel/path/to/file.rs",
            "/var/tmp/rel/path/to/file.rs",
        ),
        ("/fallback", "a.rs", "/fallback/a.rs"),
        ("/fallback", "src/main.rs", "/fallback/src/main.rs"),
        ("/fallback", "notes.txt", "/fallback/notes.txt"),
        (
            "/fallback",
            "Downloads/file.md",
            "/fallback/Downloads/file.md",
        ),
        ("/fallback", "local.txt", "/fallback/local.txt"),
        ("/fallback", "scratch.rs", "/fallback/scratch.rs"),
        (
            "/fallback",
            "nested/path/file",
            "/fallback/nested/path/file",
        ),
        ("/fallback", "./dot.txt", "/fallback/./dot.txt"),
        ("/fallback", "dir", "/fallback/dir"),
        ("/fallback", "a/b/c/d", "/fallback/a/b/c/d"),
        ("/fallback", "only.txt", "/fallback/only.txt"),
        ("/fallback", "pkg/lib.rs", "/fallback/pkg/lib.rs"),
        ("/fallback", "x", "/fallback/x"),
        ("/fallback", "x/y", "/fallback/x/y"),
        ("/fallback", "x/y/z.md", "/fallback/x/y/z.md"),
        ("/fallback", "composer.txt", "/fallback/composer.txt"),
        ("/fallback", "attach/me.md", "/fallback/attach/me.md"),
        (
            "/fallback",
            "rel/path/to/file.rs",
            "/fallback/rel/path/to/file.rs",
        ),
    ]
}

fn absolute_path_cases() -> Vec<&'static str> {
    vec![
        "/abs/tree-1/file.rs",
        "/abs/tree-2/file.rs",
        "/abs/tree-3/file.rs",
        "/abs/tree-4/file.rs",
        "/abs/tree-5/file.rs",
        "/abs/tree-6/file.rs",
        "/abs/tree-7/file.rs",
        "/abs/tree-8/file.rs",
        "/abs/tree-9/file.rs",
        "/abs/tree-10/file.rs",
        "/abs/tree-11/file.rs",
        "/abs/tree-12/file.rs",
        "/abs/tree-13/file.rs",
        "/abs/tree-14/file.rs",
        "/abs/tree-15/file.rs",
        "/abs/tree-16/file.rs",
        "/abs/tree-17/file.rs",
        "/abs/tree-18/file.rs",
        "/abs/tree-19/file.rs",
        "/abs/tree-20/file.rs",
        "/abs/tree-21/file.rs",
        "/abs/tree-22/file.rs",
        "/abs/tree-23/file.rs",
        "/abs/tree-24/file.rs",
        "/abs/tree-25/file.rs",
        "/abs/tree-26/file.rs",
        "/abs/tree-27/file.rs",
        "/abs/tree-28/file.rs",
        "/abs/tree-29/file.rs",
        "/abs/tree-30/file.rs",
        "/abs/tree-31/file.rs",
        "/abs/tree-32/file.rs",
        "/abs/tree-33/file.rs",
        "/abs/tree-34/file.rs",
        "/abs/tree-35/file.rs",
        "/abs/tree-36/file.rs",
        "/abs/tree-37/file.rs",
        "/abs/tree-38/file.rs",
        "/abs/tree-39/file.rs",
        "/abs/tree-40/file.rs",
        "/abs/tree-41/file.rs",
        "/abs/tree-42/file.rs",
        "/abs/tree-43/file.rs",
        "/abs/tree-44/file.rs",
        "/abs/tree-45/file.rs",
        "/abs/tree-46/file.rs",
        "/abs/tree-47/file.rs",
        "/abs/tree-48/file.rs",
        "/abs/tree-49/file.rs",
        "/abs/tree-50/file.rs",
        "/abs/tree-51/file.rs",
        "/abs/tree-52/file.rs",
        "/abs/tree-53/file.rs",
        "/abs/tree-54/file.rs",
        "/abs/tree-55/file.rs",
        "/abs/tree-56/file.rs",
        "/abs/tree-57/file.rs",
        "/abs/tree-58/file.rs",
        "/abs/tree-59/file.rs",
        "/abs/tree-60/file.rs",
        "/abs/tree-61/file.rs",
        "/abs/tree-62/file.rs",
        "/abs/tree-63/file.rs",
        "/abs/tree-64/file.rs",
        "/abs/tree-65/file.rs",
        "/abs/tree-66/file.rs",
        "/abs/tree-67/file.rs",
        "/abs/tree-68/file.rs",
        "/abs/tree-69/file.rs",
        "/abs/tree-70/file.rs",
        "/abs/tree-71/file.rs",
        "/abs/tree-72/file.rs",
        "/abs/tree-73/file.rs",
        "/abs/tree-74/file.rs",
        "/abs/tree-75/file.rs",
        "/abs/tree-76/file.rs",
        "/abs/tree-77/file.rs",
        "/abs/tree-78/file.rs",
        "/abs/tree-79/file.rs",
        "/abs/tree-80/file.rs",
        "/home/u/secret.md",
        "/etc/hosts",
        "/tmp/shot.png",
        "/usr/share/doc/readme",
        "/var/log/app.log",
        "/opt/bin/tool",
        "/srv/www/index.html",
        "/root/.ssh/config",
        "/home/u/Projects/ronin/Cargo.toml",
        "/home/u/Projects/ronin/crates/ronin_core/src/context.rs",
        "/tmp/with spaces/file.txt",
        "/abs/./weird.rs",
        "/abs/../other.rs",
        "/media/data/notes.md",
        "/run/user/1000/file.txt",
    ]
}

fn workspace_vs_cwd_pairs() -> Vec<(&'static str, &'static str)> {
    vec![
        ("/ws-1", "/cwd-1"),
        ("/ws-2", "/cwd-2"),
        ("/ws-3", "/cwd-3"),
        ("/ws-4", "/cwd-4"),
        ("/ws-5", "/cwd-5"),
        ("/ws-6", "/cwd-6"),
        ("/ws-7", "/cwd-7"),
        ("/ws-8", "/cwd-8"),
        ("/ws-9", "/cwd-9"),
        ("/ws-10", "/cwd-10"),
        ("/ws-11", "/cwd-11"),
        ("/ws-12", "/cwd-12"),
        ("/ws-13", "/cwd-13"),
        ("/ws-14", "/cwd-14"),
        ("/ws-15", "/cwd-15"),
        ("/ws-16", "/cwd-16"),
        ("/ws-17", "/cwd-17"),
        ("/ws-18", "/cwd-18"),
        ("/ws-19", "/cwd-19"),
        ("/ws-20", "/cwd-20"),
        ("/ws-21", "/cwd-21"),
        ("/ws-22", "/cwd-22"),
        ("/ws-23", "/cwd-23"),
        ("/ws-24", "/cwd-24"),
        ("/ws-25", "/cwd-25"),
        ("/ws-26", "/cwd-26"),
        ("/ws-27", "/cwd-27"),
        ("/ws-28", "/cwd-28"),
        ("/ws-29", "/cwd-29"),
        ("/ws-30", "/cwd-30"),
        ("/ws-31", "/cwd-31"),
        ("/ws-32", "/cwd-32"),
        ("/ws-33", "/cwd-33"),
        ("/ws-34", "/cwd-34"),
        ("/ws-35", "/cwd-35"),
        ("/ws-36", "/cwd-36"),
        ("/ws-37", "/cwd-37"),
        ("/ws-38", "/cwd-38"),
        ("/ws-39", "/cwd-39"),
        ("/ws-40", "/cwd-40"),
        ("/ws-41", "/cwd-41"),
        ("/ws-42", "/cwd-42"),
        ("/ws-43", "/cwd-43"),
        ("/ws-44", "/cwd-44"),
        ("/ws-45", "/cwd-45"),
        ("/ws-46", "/cwd-46"),
        ("/ws-47", "/cwd-47"),
        ("/ws-48", "/cwd-48"),
        ("/ws-49", "/cwd-49"),
        ("/ws-50", "/cwd-50"),
        ("/ws-51", "/cwd-51"),
        ("/ws-52", "/cwd-52"),
        ("/ws-53", "/cwd-53"),
        ("/ws-54", "/cwd-54"),
        ("/ws-55", "/cwd-55"),
        ("/ws-56", "/cwd-56"),
        ("/ws-57", "/cwd-57"),
        ("/ws-58", "/cwd-58"),
        ("/ws-59", "/cwd-59"),
        ("/ws-60", "/cwd-60"),
        ("/home/proj", "/tmp"),
        ("/a", "/b"),
        ("/long/workspace/path", "/short"),
        ("/w", "/c"),
        ("/project", "/elsewhere"),
        ("/one", "/two"),
        ("/alpha", "/beta"),
        ("/left", "/right"),
        ("/primary", "/secondary"),
        ("/bound", "/unbound"),
        ("/explicit-root", "/process-cwd"),
        ("/thread-ws", "/shell-cwd"),
    ]
}

#[test]
fn resolve_relative_paths_against_workspace_should_join_root_not_cwd() {
    let fallback = Path::new("/should-not-win");
    for (ws, rel, expected) in relative_with_workspace_cases() {
        let got = resolve_context_path(Path::new(rel), Some(Path::new(ws)), fallback);
        assert_eq!(got, PathBuf::from(expected), "ws={ws} rel={rel}");
    }
}

#[test]
fn resolve_relative_paths_without_workspace_should_join_explicit_cwd() {
    for (cwd, rel, expected) in relative_without_workspace_cases() {
        let got = resolve_context_path(Path::new(rel), None, Path::new(cwd));
        assert_eq!(got, PathBuf::from(expected), "cwd={cwd} rel={rel}");
    }
}

#[test]
fn resolve_absolute_paths_should_ignore_workspace_and_cwd() {
    let workspace = Path::new("/workspace/root");
    let fallback = Path::new("/fallback/cwd");
    for abs in absolute_path_cases() {
        let path = Path::new(abs);
        assert_eq!(
            resolve_context_path(path, Some(workspace), fallback),
            path,
            "with ws: {abs}"
        );
        assert_eq!(
            resolve_context_path(path, None, fallback),
            path,
            "without ws: {abs}"
        );
    }
}

#[test]
fn context_path_base_should_prefer_explicit_workspace_over_cwd() {
    for (ws, cwd) in workspace_vs_cwd_pairs() {
        assert_eq!(
            context_path_base(Some(Path::new(ws)), Path::new(cwd)),
            Path::new(ws)
        );
        assert_eq!(context_path_base(None, Path::new(cwd)), Path::new(cwd));
    }
}

#[test]
fn resolve_should_not_invent_git_or_implicit_cwd_workspace() {
    let requested = Path::new("src/lib.rs");
    let fallback = Path::new("/explicit-fallback");
    let got = resolve_context_path(requested, None, fallback);
    assert_eq!(got, PathBuf::from("/explicit-fallback/src/lib.rs"));
    assert!(!got.starts_with("/auto"));
    assert!(!got.components().any(|c| c.as_os_str() == ".git"));
}

#[test]
fn resolve_with_workspace_should_ignore_cwd_that_looks_like_git_root() {
    let cases: &[(&str, &str, &str)] = &[
        ("/bound/ws-1", "/repo-with-git-1", "src/f1.rs"),
        ("/bound/ws-2", "/repo-with-git-2", "src/f2.rs"),
        ("/bound/ws-3", "/repo-with-git-3", "src/f3.rs"),
        ("/bound/ws-4", "/repo-with-git-4", "src/f4.rs"),
        ("/bound/ws-5", "/repo-with-git-5", "src/f5.rs"),
        ("/bound/ws-6", "/repo-with-git-6", "src/f6.rs"),
        ("/bound/ws-7", "/repo-with-git-7", "src/f7.rs"),
        ("/bound/ws-8", "/repo-with-git-8", "src/f8.rs"),
        ("/bound/ws-9", "/repo-with-git-9", "src/f9.rs"),
        ("/bound/ws-10", "/repo-with-git-10", "src/f10.rs"),
        ("/bound/ws-11", "/repo-with-git-11", "src/f11.rs"),
        ("/bound/ws-12", "/repo-with-git-12", "src/f12.rs"),
        ("/bound/ws-13", "/repo-with-git-13", "src/f13.rs"),
        ("/bound/ws-14", "/repo-with-git-14", "src/f14.rs"),
        ("/bound/ws-15", "/repo-with-git-15", "src/f15.rs"),
        ("/bound/ws-16", "/repo-with-git-16", "src/f16.rs"),
        ("/bound/ws-17", "/repo-with-git-17", "src/f17.rs"),
        ("/bound/ws-18", "/repo-with-git-18", "src/f18.rs"),
        ("/bound/ws-19", "/repo-with-git-19", "src/f19.rs"),
        ("/bound/ws-20", "/repo-with-git-20", "src/f20.rs"),
        ("/bound/ws-21", "/repo-with-git-21", "src/f21.rs"),
        ("/bound/ws-22", "/repo-with-git-22", "src/f22.rs"),
        ("/bound/ws-23", "/repo-with-git-23", "src/f23.rs"),
        ("/bound/ws-24", "/repo-with-git-24", "src/f24.rs"),
        ("/bound/ws-25", "/repo-with-git-25", "src/f25.rs"),
        ("/bound/ws-26", "/repo-with-git-26", "src/f26.rs"),
        ("/bound/ws-27", "/repo-with-git-27", "src/f27.rs"),
        ("/bound/ws-28", "/repo-with-git-28", "src/f28.rs"),
        ("/bound/ws-29", "/repo-with-git-29", "src/f29.rs"),
        ("/bound/ws-30", "/repo-with-git-30", "src/f30.rs"),
        ("/bound/ws-31", "/repo-with-git-31", "src/f31.rs"),
        ("/bound/ws-32", "/repo-with-git-32", "src/f32.rs"),
        ("/bound/ws-33", "/repo-with-git-33", "src/f33.rs"),
        ("/bound/ws-34", "/repo-with-git-34", "src/f34.rs"),
        ("/bound/ws-35", "/repo-with-git-35", "src/f35.rs"),
        ("/bound/ws-36", "/repo-with-git-36", "src/f36.rs"),
        ("/bound/ws-37", "/repo-with-git-37", "src/f37.rs"),
        ("/bound/ws-38", "/repo-with-git-38", "src/f38.rs"),
        ("/bound/ws-39", "/repo-with-git-39", "src/f39.rs"),
        ("/bound/ws-40", "/repo-with-git-40", "src/f40.rs"),
        ("/bound/ws-41", "/repo-with-git-41", "src/f41.rs"),
        ("/bound/ws-42", "/repo-with-git-42", "src/f42.rs"),
        ("/bound/ws-43", "/repo-with-git-43", "src/f43.rs"),
        ("/bound/ws-44", "/repo-with-git-44", "src/f44.rs"),
        ("/bound/ws-45", "/repo-with-git-45", "src/f45.rs"),
        ("/bound/ws-46", "/repo-with-git-46", "src/f46.rs"),
        ("/bound/ws-47", "/repo-with-git-47", "src/f47.rs"),
        ("/bound/ws-48", "/repo-with-git-48", "src/f48.rs"),
        ("/bound/ws-49", "/repo-with-git-49", "src/f49.rs"),
        ("/bound/ws-50", "/repo-with-git-50", "src/f50.rs"),
        ("/bound/ws-51", "/repo-with-git-51", "src/f51.rs"),
        ("/bound/ws-52", "/repo-with-git-52", "src/f52.rs"),
        ("/bound/ws-53", "/repo-with-git-53", "src/f53.rs"),
        ("/bound/ws-54", "/repo-with-git-54", "src/f54.rs"),
        ("/bound/ws-55", "/repo-with-git-55", "src/f55.rs"),
        ("/bound/ws-56", "/repo-with-git-56", "src/f56.rs"),
        ("/bound/ws-57", "/repo-with-git-57", "src/f57.rs"),
        ("/bound/ws-58", "/repo-with-git-58", "src/f58.rs"),
        ("/bound/ws-59", "/repo-with-git-59", "src/f59.rs"),
        ("/bound/ws-60", "/repo-with-git-60", "src/f60.rs"),
        ("/bound/ws-61", "/repo-with-git-61", "src/f61.rs"),
        ("/bound/ws-62", "/repo-with-git-62", "src/f62.rs"),
        ("/bound/ws-63", "/repo-with-git-63", "src/f63.rs"),
        ("/bound/ws-64", "/repo-with-git-64", "src/f64.rs"),
        ("/bound/ws-65", "/repo-with-git-65", "src/f65.rs"),
        ("/bound/ws-66", "/repo-with-git-66", "src/f66.rs"),
        ("/bound/ws-67", "/repo-with-git-67", "src/f67.rs"),
        ("/bound/ws-68", "/repo-with-git-68", "src/f68.rs"),
        ("/bound/ws-69", "/repo-with-git-69", "src/f69.rs"),
        ("/bound/ws-70", "/repo-with-git-70", "src/f70.rs"),
        ("/bound/ws-71", "/repo-with-git-71", "src/f71.rs"),
        ("/bound/ws-72", "/repo-with-git-72", "src/f72.rs"),
        ("/bound/ws-73", "/repo-with-git-73", "src/f73.rs"),
        ("/bound/ws-74", "/repo-with-git-74", "src/f74.rs"),
        ("/bound/ws-75", "/repo-with-git-75", "src/f75.rs"),
        ("/bound/ws-76", "/repo-with-git-76", "src/f76.rs"),
        ("/bound/ws-77", "/repo-with-git-77", "src/f77.rs"),
        ("/bound/ws-78", "/repo-with-git-78", "src/f78.rs"),
        ("/bound/ws-79", "/repo-with-git-79", "src/f79.rs"),
        ("/bound/ws-80", "/repo-with-git-80", "src/f80.rs"),
    ];
    for (ws, cwd, rel) in cases {
        let got = resolve_context_path(rel, Some(Path::new(ws)), Path::new(cwd));
        assert_eq!(got, PathBuf::from(format!("{ws}/{rel}")));
        assert!(!got.starts_with(cwd), "must not use cwd={cwd}");
    }
}

#[test]
fn launch_attach_style_absolute_paths_remain_stable_under_any_workspace() {
    let paths: &[&str] = &[
        "/launch/attach/file-1.md",
        "/launch/attach/file-2.md",
        "/launch/attach/file-3.md",
        "/launch/attach/file-4.md",
        "/launch/attach/file-5.md",
        "/launch/attach/file-6.md",
        "/launch/attach/file-7.md",
        "/launch/attach/file-8.md",
        "/launch/attach/file-9.md",
        "/launch/attach/file-10.md",
        "/launch/attach/file-11.md",
        "/launch/attach/file-12.md",
        "/launch/attach/file-13.md",
        "/launch/attach/file-14.md",
        "/launch/attach/file-15.md",
        "/launch/attach/file-16.md",
        "/launch/attach/file-17.md",
        "/launch/attach/file-18.md",
        "/launch/attach/file-19.md",
        "/launch/attach/file-20.md",
        "/launch/attach/file-21.md",
        "/launch/attach/file-22.md",
        "/launch/attach/file-23.md",
        "/launch/attach/file-24.md",
        "/launch/attach/file-25.md",
        "/launch/attach/file-26.md",
        "/launch/attach/file-27.md",
        "/launch/attach/file-28.md",
        "/launch/attach/file-29.md",
        "/launch/attach/file-30.md",
        "/launch/attach/file-31.md",
        "/launch/attach/file-32.md",
        "/launch/attach/file-33.md",
        "/launch/attach/file-34.md",
        "/launch/attach/file-35.md",
        "/launch/attach/file-36.md",
        "/launch/attach/file-37.md",
        "/launch/attach/file-38.md",
        "/launch/attach/file-39.md",
        "/launch/attach/file-40.md",
        "/launch/attach/file-41.md",
        "/launch/attach/file-42.md",
        "/launch/attach/file-43.md",
        "/launch/attach/file-44.md",
        "/launch/attach/file-45.md",
        "/launch/attach/file-46.md",
        "/launch/attach/file-47.md",
        "/launch/attach/file-48.md",
        "/launch/attach/file-49.md",
        "/launch/attach/file-50.md",
        "/launch/attach/file-51.md",
        "/launch/attach/file-52.md",
        "/launch/attach/file-53.md",
        "/launch/attach/file-54.md",
        "/launch/attach/file-55.md",
        "/launch/attach/file-56.md",
        "/launch/attach/file-57.md",
        "/launch/attach/file-58.md",
        "/launch/attach/file-59.md",
        "/launch/attach/file-60.md",
    ];
    let workspaces = ["/ws-a", "/ws-b", "/ws-c", "/tmp/other"];
    for abs in paths {
        for ws in workspaces {
            let got = resolve_context_path(abs, Some(Path::new(ws)), Path::new("/cwd"));
            assert_eq!(got, PathBuf::from(*abs));
        }
        let got = resolve_context_path(abs, None, Path::new("/cwd"));
        assert_eq!(got, PathBuf::from(*abs));
    }
}

#[test]
fn resolve_nested_relative_segments_against_many_workspace_roots() {
    let segments: &[&str] = &[
        "layer1/mod.rs",
        "layer2/mod.rs",
        "layer3/mod.rs",
        "layer4/mod.rs",
        "layer5/mod.rs",
        "layer6/mod.rs",
        "layer7/mod.rs",
        "layer8/mod.rs",
        "layer9/mod.rs",
        "layer10/mod.rs",
        "layer11/mod.rs",
        "layer12/mod.rs",
        "layer13/mod.rs",
        "layer14/mod.rs",
        "layer15/mod.rs",
        "layer16/mod.rs",
        "layer17/mod.rs",
        "layer18/mod.rs",
        "layer19/mod.rs",
        "layer20/mod.rs",
        "layer21/mod.rs",
        "layer22/mod.rs",
        "layer23/mod.rs",
        "layer24/mod.rs",
        "layer25/mod.rs",
        "layer26/mod.rs",
        "layer27/mod.rs",
        "layer28/mod.rs",
        "layer29/mod.rs",
        "layer30/mod.rs",
        "layer31/mod.rs",
        "layer32/mod.rs",
        "layer33/mod.rs",
        "layer34/mod.rs",
        "layer35/mod.rs",
        "layer36/mod.rs",
        "layer37/mod.rs",
        "layer38/mod.rs",
        "layer39/mod.rs",
        "layer40/mod.rs",
        "layer41/mod.rs",
        "layer42/mod.rs",
        "layer43/mod.rs",
        "layer44/mod.rs",
        "layer45/mod.rs",
        "layer46/mod.rs",
        "layer47/mod.rs",
        "layer48/mod.rs",
        "layer49/mod.rs",
        "layer50/mod.rs",
        "layer51/mod.rs",
        "layer52/mod.rs",
        "layer53/mod.rs",
        "layer54/mod.rs",
        "layer55/mod.rs",
        "layer56/mod.rs",
        "layer57/mod.rs",
        "layer58/mod.rs",
        "layer59/mod.rs",
        "layer60/mod.rs",
        "layer61/mod.rs",
        "layer62/mod.rs",
        "layer63/mod.rs",
        "layer64/mod.rs",
        "layer65/mod.rs",
        "layer66/mod.rs",
        "layer67/mod.rs",
        "layer68/mod.rs",
        "layer69/mod.rs",
        "layer70/mod.rs",
        "layer71/mod.rs",
        "layer72/mod.rs",
        "layer73/mod.rs",
        "layer74/mod.rs",
        "layer75/mod.rs",
        "layer76/mod.rs",
        "layer77/mod.rs",
        "layer78/mod.rs",
        "layer79/mod.rs",
        "layer80/mod.rs",
        "layer81/mod.rs",
        "layer82/mod.rs",
        "layer83/mod.rs",
        "layer84/mod.rs",
        "layer85/mod.rs",
        "layer86/mod.rs",
        "layer87/mod.rs",
        "layer88/mod.rs",
        "layer89/mod.rs",
        "layer90/mod.rs",
        "layer91/mod.rs",
        "layer92/mod.rs",
        "layer93/mod.rs",
        "layer94/mod.rs",
        "layer95/mod.rs",
        "layer96/mod.rs",
        "layer97/mod.rs",
        "layer98/mod.rs",
        "layer99/mod.rs",
        "layer100/mod.rs",
        "layer101/mod.rs",
        "layer102/mod.rs",
        "layer103/mod.rs",
        "layer104/mod.rs",
        "layer105/mod.rs",
        "layer106/mod.rs",
        "layer107/mod.rs",
        "layer108/mod.rs",
        "layer109/mod.rs",
        "layer110/mod.rs",
        "layer111/mod.rs",
        "layer112/mod.rs",
        "layer113/mod.rs",
        "layer114/mod.rs",
        "layer115/mod.rs",
        "layer116/mod.rs",
        "layer117/mod.rs",
        "layer118/mod.rs",
        "layer119/mod.rs",
        "layer120/mod.rs",
    ];
    let roots: &[&str] = &[
        "/workspace/root-1",
        "/workspace/root-2",
        "/workspace/root-3",
        "/workspace/root-4",
        "/workspace/root-5",
        "/workspace/root-6",
        "/workspace/root-7",
        "/workspace/root-8",
        "/workspace/root-9",
        "/workspace/root-10",
        "/workspace/root-11",
        "/workspace/root-12",
        "/workspace/root-13",
        "/workspace/root-14",
        "/workspace/root-15",
        "/workspace/root-16",
        "/workspace/root-17",
        "/workspace/root-18",
        "/workspace/root-19",
        "/workspace/root-20",
        "/workspace/root-21",
        "/workspace/root-22",
        "/workspace/root-23",
        "/workspace/root-24",
        "/workspace/root-25",
        "/workspace/root-26",
        "/workspace/root-27",
        "/workspace/root-28",
        "/workspace/root-29",
        "/workspace/root-30",
        "/workspace/root-31",
        "/workspace/root-32",
        "/workspace/root-33",
        "/workspace/root-34",
        "/workspace/root-35",
        "/workspace/root-36",
        "/workspace/root-37",
        "/workspace/root-38",
        "/workspace/root-39",
        "/workspace/root-40",
    ];
    let cwd = Path::new("/must-not-win");
    for root in roots {
        for seg in segments {
            let got = resolve_context_path(*seg, Some(Path::new(root)), cwd);
            assert_eq!(got, PathBuf::from(format!("{root}/{seg}")));
        }
    }
}

#[test]
fn resolve_relative_folder_style_paths_use_workspace_when_bound() {
    let folders: &[&str] = &[
        "src",
        "tests",
        "docs",
        "crates",
        "scripts",
        "fixtures",
        "loop",
        "assets",
        "pkg/a",
        "pkg/b",
        "pkg/c",
        "vendor/lib",
        "examples/basic",
        "examples/advanced",
        "dir-1",
        "dir-2",
        "dir-3",
        "dir-4",
        "dir-5",
        "dir-6",
        "dir-7",
        "dir-8",
        "dir-9",
        "dir-10",
        "dir-11",
        "dir-12",
        "dir-13",
        "dir-14",
        "dir-15",
        "dir-16",
        "dir-17",
        "dir-18",
        "dir-19",
        "dir-20",
        "dir-21",
        "dir-22",
        "dir-23",
        "dir-24",
        "dir-25",
        "dir-26",
        "dir-27",
        "dir-28",
        "dir-29",
        "dir-30",
        "dir-31",
        "dir-32",
        "dir-33",
        "dir-34",
        "dir-35",
        "dir-36",
        "dir-37",
        "dir-38",
        "dir-39",
        "dir-40",
        "dir-41",
        "dir-42",
        "dir-43",
        "dir-44",
        "dir-45",
        "dir-46",
        "dir-47",
        "dir-48",
        "dir-49",
        "dir-50",
        "dir-51",
        "dir-52",
        "dir-53",
        "dir-54",
        "dir-55",
        "dir-56",
        "dir-57",
        "dir-58",
        "dir-59",
        "dir-60",
        "dir-61",
        "dir-62",
        "dir-63",
        "dir-64",
        "dir-65",
        "dir-66",
        "dir-67",
        "dir-68",
        "dir-69",
        "dir-70",
        "dir-71",
        "dir-72",
        "dir-73",
        "dir-74",
        "dir-75",
        "dir-76",
        "dir-77",
        "dir-78",
        "dir-79",
        "dir-80",
    ];
    let ws = Path::new("/bound/workspace");
    let cwd = Path::new("/cwd");
    for folder in folders {
        let got = resolve_context_path(*folder, Some(ws), cwd);
        assert_eq!(got, PathBuf::from(format!("/bound/workspace/{folder}")));
    }
}

#[test]
fn resolve_dotdot_segments_still_prefix_with_explicit_workspace() {
    let cases: &[(&str, &str)] = &[
        ("/ws/base-1", "sub/../sibling-1.rs"),
        ("/ws/base-2", "sub/../sibling-2.rs"),
        ("/ws/base-3", "sub/../sibling-3.rs"),
        ("/ws/base-4", "sub/../sibling-4.rs"),
        ("/ws/base-5", "sub/../sibling-5.rs"),
        ("/ws/base-6", "sub/../sibling-6.rs"),
        ("/ws/base-7", "sub/../sibling-7.rs"),
        ("/ws/base-8", "sub/../sibling-8.rs"),
        ("/ws/base-9", "sub/../sibling-9.rs"),
        ("/ws/base-10", "sub/../sibling-10.rs"),
        ("/ws/base-11", "sub/../sibling-11.rs"),
        ("/ws/base-12", "sub/../sibling-12.rs"),
        ("/ws/base-13", "sub/../sibling-13.rs"),
        ("/ws/base-14", "sub/../sibling-14.rs"),
        ("/ws/base-15", "sub/../sibling-15.rs"),
        ("/ws/base-16", "sub/../sibling-16.rs"),
        ("/ws/base-17", "sub/../sibling-17.rs"),
        ("/ws/base-18", "sub/../sibling-18.rs"),
        ("/ws/base-19", "sub/../sibling-19.rs"),
        ("/ws/base-20", "sub/../sibling-20.rs"),
        ("/ws/base-21", "sub/../sibling-21.rs"),
        ("/ws/base-22", "sub/../sibling-22.rs"),
        ("/ws/base-23", "sub/../sibling-23.rs"),
        ("/ws/base-24", "sub/../sibling-24.rs"),
        ("/ws/base-25", "sub/../sibling-25.rs"),
        ("/ws/base-26", "sub/../sibling-26.rs"),
        ("/ws/base-27", "sub/../sibling-27.rs"),
        ("/ws/base-28", "sub/../sibling-28.rs"),
        ("/ws/base-29", "sub/../sibling-29.rs"),
        ("/ws/base-30", "sub/../sibling-30.rs"),
        ("/ws/base-31", "sub/../sibling-31.rs"),
        ("/ws/base-32", "sub/../sibling-32.rs"),
        ("/ws/base-33", "sub/../sibling-33.rs"),
        ("/ws/base-34", "sub/../sibling-34.rs"),
        ("/ws/base-35", "sub/../sibling-35.rs"),
        ("/ws/base-36", "sub/../sibling-36.rs"),
        ("/ws/base-37", "sub/../sibling-37.rs"),
        ("/ws/base-38", "sub/../sibling-38.rs"),
        ("/ws/base-39", "sub/../sibling-39.rs"),
        ("/ws/base-40", "sub/../sibling-40.rs"),
        ("/ws/base-41", "sub/../sibling-41.rs"),
        ("/ws/base-42", "sub/../sibling-42.rs"),
        ("/ws/base-43", "sub/../sibling-43.rs"),
        ("/ws/base-44", "sub/../sibling-44.rs"),
        ("/ws/base-45", "sub/../sibling-45.rs"),
        ("/ws/base-46", "sub/../sibling-46.rs"),
        ("/ws/base-47", "sub/../sibling-47.rs"),
        ("/ws/base-48", "sub/../sibling-48.rs"),
        ("/ws/base-49", "sub/../sibling-49.rs"),
        ("/ws/base-50", "sub/../sibling-50.rs"),
    ];
    let cwd = Path::new("/cwd");
    for (ws, rel) in cases {
        let got = resolve_context_path(rel, Some(Path::new(ws)), cwd);
        assert_eq!(got, PathBuf::from(format!("{ws}/{rel}")));
    }
}
