//! Table-driven workspace index cases (#73).

use std::path::Path;
use std::sync::atomic::AtomicBool;
use std::time::Duration;

use ronin_core::{
    collect_workspace_index_documents, workspace_index_storage_path, FolderListPolicy,
    WorkspaceIndexCaps, WorkspaceIndexPhase, WORKSPACE_INDEX_MAX_BYTES, WORKSPACE_INDEX_MAX_DEPTH,
    WORKSPACE_INDEX_MAX_ENTRIES, WORKSPACE_INDEX_MAX_FILE_BYTES, WORKSPACE_INDEX_STORAGE_DIR,
};
use tempfile::TempDir;

fn write_n(root: &Path, n: usize, prefix: &str, body: &str) {
    std::fs::create_dir_all(root).unwrap();
    for i in 0..n {
        std::fs::write(root.join(format!("{prefix}{i:04}.txt")), body).unwrap();
    }
}

#[test]
fn phase_parse_round_trips_all_labels() {
    let labels = [
        ("absent", WorkspaceIndexPhase::Absent),
        ("running", WorkspaceIndexPhase::Running),
        ("done", WorkspaceIndexPhase::Done),
        ("failed", WorkspaceIndexPhase::Failed),
        ("cancelled", WorkspaceIndexPhase::Cancelled),
    ];
    for (label, phase) in labels {
        assert_eq!(WorkspaceIndexPhase::parse(label), Some(phase));
        assert_eq!(phase.as_str(), label);
    }
    assert_eq!(WorkspaceIndexPhase::parse("nope"), None);
    assert_eq!(WorkspaceIndexPhase::parse(""), None);
    assert_eq!(WorkspaceIndexPhase::parse("DONE"), None);
}

#[test]
fn storage_paths_stay_under_workspace_indexes_dir() {
    let data = Path::new("/tmp/ronin-data-fixture");
    let ids: &[&str] = &[
        "thread-0000",
        "thread-0001",
        "thread-0002",
        "thread-0003",
        "thread-0004",
        "thread-0005",
        "thread-0006",
        "thread-0007",
        "thread-0008",
        "thread-0009",
        "thread-0010",
        "thread-0011",
        "thread-0012",
        "thread-0013",
        "thread-0014",
        "thread-0015",
        "thread-0016",
        "thread-0017",
        "thread-0018",
        "thread-0019",
        "thread-0020",
        "thread-0021",
        "thread-0022",
        "thread-0023",
        "thread-0024",
        "thread-0025",
        "thread-0026",
        "thread-0027",
        "thread-0028",
        "thread-0029",
        "thread-0030",
        "thread-0031",
        "thread-0032",
        "thread-0033",
        "thread-0034",
        "thread-0035",
        "thread-0036",
        "thread-0037",
        "thread-0038",
        "thread-0039",
        "thread-0040",
        "thread-0041",
        "thread-0042",
        "thread-0043",
        "thread-0044",
        "thread-0045",
        "thread-0046",
        "thread-0047",
        "thread-0048",
        "thread-0049",
        "thread-0050",
        "thread-0051",
        "thread-0052",
        "thread-0053",
        "thread-0054",
        "thread-0055",
        "thread-0056",
        "thread-0057",
        "thread-0058",
        "thread-0059",
        "thread-0060",
        "thread-0061",
        "thread-0062",
        "thread-0063",
        "thread-0064",
        "thread-0065",
        "thread-0066",
        "thread-0067",
        "thread-0068",
        "thread-0069",
        "thread-0070",
        "thread-0071",
        "thread-0072",
        "thread-0073",
        "thread-0074",
        "thread-0075",
        "thread-0076",
        "thread-0077",
        "thread-0078",
        "thread-0079",
        "thread-0080",
        "thread-0081",
        "thread-0082",
        "thread-0083",
        "thread-0084",
        "thread-0085",
        "thread-0086",
        "thread-0087",
        "thread-0088",
        "thread-0089",
        "thread-0090",
        "thread-0091",
        "thread-0092",
        "thread-0093",
        "thread-0094",
        "thread-0095",
        "thread-0096",
        "thread-0097",
        "thread-0098",
        "thread-0099",
        "thread-0100",
        "thread-0101",
        "thread-0102",
        "thread-0103",
        "thread-0104",
        "thread-0105",
        "thread-0106",
        "thread-0107",
        "thread-0108",
        "thread-0109",
        "thread-0110",
        "thread-0111",
        "thread-0112",
        "thread-0113",
        "thread-0114",
        "thread-0115",
        "thread-0116",
        "thread-0117",
        "thread-0118",
        "thread-0119",
    ];
    for id in ids {
        let path = workspace_index_storage_path(data, id);
        assert!(path.starts_with(data.join(WORKSPACE_INDEX_STORAGE_DIR)));
        assert!(path.ends_with(format!("{id}.db")));
    }
}

#[test]
fn collect_entry_caps_table() {
    let caps_list: &[(usize, usize)] = &[
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (12, 12),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (18, 18),
        (19, 19),
        (20, 20),
        (21, 21),
        (22, 22),
        (23, 23),
        (24, 24),
        (25, 25),
        (26, 26),
        (27, 27),
        (28, 28),
        (29, 29),
        (30, 30),
        (31, 31),
        (32, 32),
        (33, 33),
        (34, 34),
        (35, 35),
        (36, 36),
        (37, 37),
        (38, 38),
        (39, 39),
        (40, 40),
        (50, 50),
        (60, 60),
        (70, 70),
        (80, 80),
        (90, 90),
        (100, 100),
        (110, 110),
        (120, 120),
        (130, 130),
        (140, 140),
        (150, 150),
        (160, 160),
        (170, 170),
        (180, 180),
        (190, 190),
        (200, 200),
    ];
    for &(max_entries, expect) in caps_list {
        let temp = TempDir::new().unwrap();
        let root = temp.path().join("t");
        write_n(&root, 250, "f", "body");
        let caps = WorkspaceIndexCaps {
            max_entries,
            max_bytes: WORKSPACE_INDEX_MAX_BYTES,
            max_depth: WORKSPACE_INDEX_MAX_DEPTH,
            max_file_bytes: WORKSPACE_INDEX_MAX_FILE_BYTES,
            max_duration: Duration::from_secs(30),
        };
        let result = collect_workspace_index_documents(
            &root,
            &FolderListPolicy::default(),
            &caps,
            &AtomicBool::new(false),
        );
        assert_eq!(result.documents.len(), expect, "max_entries={max_entries}");
        assert!(result.truncated, "max_entries={max_entries}");
    }
}

#[test]
fn collect_byte_caps_table() {
    let bodies: &[(&str, u64)] = &[
        ("xxxxxxxxxx", 10),
        ("xxxxxxxxxxx", 11),
        ("xxxxxxxxxxxx", 12),
        ("xxxxxxxxxxxxx", 13),
        ("xxxxxxxxxxxxxx", 14),
        ("xxxxxxxxxxxxxxx", 15),
        ("xxxxxxxxxxxxxxxx", 16),
        ("xxxxxxxxxxxxxxxxx", 17),
        ("xxxxxxxxxxxxxxxxxx", 18),
        ("xxxxxxxxxxxxxxxxxxx", 19),
        ("xxxxxxxxxxxxxxxxxxxx", 20),
        ("xxxxxxxxxxxxxxxxxxxxx", 21),
        ("xxxxxxxxxxxxxxxxxxxxxx", 22),
        ("xxxxxxxxxxxxxxxxxxxxxxx", 23),
        ("xxxxxxxxxxxxxxxxxxxxxxxx", 24),
        ("xxxxxxxxxxxxxxxxxxxxxxxxx", 25),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxx", 26),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxx", 27),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxx", 28),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 29),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 30),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 31),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 32),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 33),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 34),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 35),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 36),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 37),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 38),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 39),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 40),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 41),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 42),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 43),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 44),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 45),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 46),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 47),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 48),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 49),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 50),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 51),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 52),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 53),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 54),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 55),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 56),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 57),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 58),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 59),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 60),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 61),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 62),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 63),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 64),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 65),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 66),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 67),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 68),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 69),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 70),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 71),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 72),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 73),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 74),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 75),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 76),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 77),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 78),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 79),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 80),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 81),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 82),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 83),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 84),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 85),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 86),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 87),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 88),
        ("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", 89),
    ];
    for (body, blen) in bodies {
        let temp = TempDir::new().unwrap();
        let root = temp.path().join("t");
        write_n(&root, 20, "b", body);
        let caps = WorkspaceIndexCaps {
            max_entries: WORKSPACE_INDEX_MAX_ENTRIES,
            max_bytes: *blen, // only first file fits exactly once
            max_depth: 4,
            max_file_bytes: WORKSPACE_INDEX_MAX_FILE_BYTES,
            max_duration: Duration::from_secs(30),
        };
        let result = collect_workspace_index_documents(
            &root,
            &FolderListPolicy::default(),
            &caps,
            &AtomicBool::new(false),
        );
        assert!(result.documents.len() <= 1, "blen={blen}");
        assert!(result.truncated || result.documents.is_empty());
    }
}

#[test]
fn collect_depth_caps_table() {
    let depths: &[usize] = &[
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
    ];
    for &max_depth in depths {
        let temp = TempDir::new().unwrap();
        let mut dir = temp.path().join("root");
        std::fs::create_dir_all(&dir).unwrap();
        // nest 10 levels with a file at each
        for level in 0..10 {
            std::fs::write(dir.join(format!("f{level}.txt")), "d").unwrap();
            dir = dir.join(format!("d{level}"));
            std::fs::create_dir_all(&dir).unwrap();
        }
        let root = temp.path().join("root");
        let caps = WorkspaceIndexCaps {
            max_entries: 100,
            max_bytes: WORKSPACE_INDEX_MAX_BYTES,
            max_depth,
            max_file_bytes: WORKSPACE_INDEX_MAX_FILE_BYTES,
            max_duration: Duration::from_secs(30),
        };
        let result = collect_workspace_index_documents(
            &root,
            &FolderListPolicy::default(),
            &caps,
            &AtomicBool::new(false),
        );
        // files at depth > max_depth should be omitted
        for doc in &result.documents {
            let depth = doc.relative_path.matches('/').count();
            assert!(
                depth <= max_depth,
                "{} depth {} > {}",
                doc.relative_path,
                depth,
                max_depth
            );
        }
    }
}

#[test]
fn collect_pre_cancelled_many_trees() {
    let names: &[&str] = &[
        "tree_000", "tree_001", "tree_002", "tree_003", "tree_004", "tree_005", "tree_006",
        "tree_007", "tree_008", "tree_009", "tree_010", "tree_011", "tree_012", "tree_013",
        "tree_014", "tree_015", "tree_016", "tree_017", "tree_018", "tree_019", "tree_020",
        "tree_021", "tree_022", "tree_023", "tree_024", "tree_025", "tree_026", "tree_027",
        "tree_028", "tree_029", "tree_030", "tree_031", "tree_032", "tree_033", "tree_034",
        "tree_035", "tree_036", "tree_037", "tree_038", "tree_039", "tree_040", "tree_041",
        "tree_042", "tree_043", "tree_044", "tree_045", "tree_046", "tree_047", "tree_048",
        "tree_049", "tree_050", "tree_051", "tree_052", "tree_053", "tree_054", "tree_055",
        "tree_056", "tree_057", "tree_058", "tree_059", "tree_060", "tree_061", "tree_062",
        "tree_063", "tree_064", "tree_065", "tree_066", "tree_067", "tree_068", "tree_069",
        "tree_070", "tree_071", "tree_072", "tree_073", "tree_074", "tree_075", "tree_076",
        "tree_077", "tree_078", "tree_079", "tree_080", "tree_081", "tree_082", "tree_083",
        "tree_084", "tree_085", "tree_086", "tree_087", "tree_088", "tree_089", "tree_090",
        "tree_091", "tree_092", "tree_093", "tree_094", "tree_095", "tree_096", "tree_097",
        "tree_098", "tree_099",
    ];
    for name in names {
        let temp = TempDir::new().unwrap();
        let root = temp.path().join(name);
        write_n(&root, 15, "c", "cancel-me");
        let result = collect_workspace_index_documents(
            &root,
            &FolderListPolicy::default(),
            &WorkspaceIndexCaps::default(),
            &AtomicBool::new(true),
        );
        assert!(result.cancelled, "{name}");
        assert!(result.truncated, "{name}");
        assert!(result.documents.len() < 15, "{name}");
    }
}

#[test]
fn cases_absent_info_defaults_grid() {
    let markers: &[&str] = &[
        "absent_marker_000",
        "absent_marker_001",
        "absent_marker_002",
        "absent_marker_003",
        "absent_marker_004",
        "absent_marker_005",
        "absent_marker_006",
        "absent_marker_007",
        "absent_marker_008",
        "absent_marker_009",
        "absent_marker_010",
        "absent_marker_011",
        "absent_marker_012",
        "absent_marker_013",
        "absent_marker_014",
        "absent_marker_015",
        "absent_marker_016",
        "absent_marker_017",
        "absent_marker_018",
        "absent_marker_019",
        "absent_marker_020",
        "absent_marker_021",
        "absent_marker_022",
        "absent_marker_023",
        "absent_marker_024",
        "absent_marker_025",
        "absent_marker_026",
        "absent_marker_027",
        "absent_marker_028",
        "absent_marker_029",
        "absent_marker_030",
        "absent_marker_031",
        "absent_marker_032",
        "absent_marker_033",
        "absent_marker_034",
        "absent_marker_035",
        "absent_marker_036",
        "absent_marker_037",
        "absent_marker_038",
        "absent_marker_039",
        "absent_marker_040",
        "absent_marker_041",
        "absent_marker_042",
        "absent_marker_043",
        "absent_marker_044",
        "absent_marker_045",
        "absent_marker_046",
        "absent_marker_047",
        "absent_marker_048",
        "absent_marker_049",
        "absent_marker_050",
        "absent_marker_051",
        "absent_marker_052",
        "absent_marker_053",
        "absent_marker_054",
        "absent_marker_055",
        "absent_marker_056",
        "absent_marker_057",
        "absent_marker_058",
        "absent_marker_059",
        "absent_marker_060",
        "absent_marker_061",
        "absent_marker_062",
        "absent_marker_063",
        "absent_marker_064",
        "absent_marker_065",
        "absent_marker_066",
        "absent_marker_067",
        "absent_marker_068",
        "absent_marker_069",
        "absent_marker_070",
        "absent_marker_071",
        "absent_marker_072",
        "absent_marker_073",
        "absent_marker_074",
        "absent_marker_075",
        "absent_marker_076",
        "absent_marker_077",
        "absent_marker_078",
        "absent_marker_079",
        "absent_marker_080",
        "absent_marker_081",
        "absent_marker_082",
        "absent_marker_083",
        "absent_marker_084",
        "absent_marker_085",
        "absent_marker_086",
        "absent_marker_087",
        "absent_marker_088",
        "absent_marker_089",
        "absent_marker_090",
        "absent_marker_091",
        "absent_marker_092",
        "absent_marker_093",
        "absent_marker_094",
        "absent_marker_095",
        "absent_marker_096",
        "absent_marker_097",
        "absent_marker_098",
        "absent_marker_099",
        "absent_marker_100",
        "absent_marker_101",
        "absent_marker_102",
        "absent_marker_103",
        "absent_marker_104",
        "absent_marker_105",
        "absent_marker_106",
        "absent_marker_107",
        "absent_marker_108",
        "absent_marker_109",
        "absent_marker_110",
        "absent_marker_111",
        "absent_marker_112",
        "absent_marker_113",
        "absent_marker_114",
        "absent_marker_115",
        "absent_marker_116",
        "absent_marker_117",
        "absent_marker_118",
        "absent_marker_119",
        "absent_marker_120",
        "absent_marker_121",
        "absent_marker_122",
        "absent_marker_123",
        "absent_marker_124",
        "absent_marker_125",
        "absent_marker_126",
        "absent_marker_127",
        "absent_marker_128",
        "absent_marker_129",
        "absent_marker_130",
        "absent_marker_131",
        "absent_marker_132",
        "absent_marker_133",
        "absent_marker_134",
        "absent_marker_135",
        "absent_marker_136",
        "absent_marker_137",
        "absent_marker_138",
        "absent_marker_139",
        "absent_marker_140",
        "absent_marker_141",
        "absent_marker_142",
        "absent_marker_143",
        "absent_marker_144",
        "absent_marker_145",
        "absent_marker_146",
        "absent_marker_147",
        "absent_marker_148",
        "absent_marker_149",
        "absent_marker_150",
        "absent_marker_151",
        "absent_marker_152",
        "absent_marker_153",
        "absent_marker_154",
        "absent_marker_155",
        "absent_marker_156",
        "absent_marker_157",
        "absent_marker_158",
        "absent_marker_159",
        "absent_marker_160",
        "absent_marker_161",
        "absent_marker_162",
        "absent_marker_163",
        "absent_marker_164",
        "absent_marker_165",
        "absent_marker_166",
        "absent_marker_167",
        "absent_marker_168",
        "absent_marker_169",
        "absent_marker_170",
        "absent_marker_171",
        "absent_marker_172",
        "absent_marker_173",
        "absent_marker_174",
        "absent_marker_175",
        "absent_marker_176",
        "absent_marker_177",
        "absent_marker_178",
        "absent_marker_179",
        "absent_marker_180",
        "absent_marker_181",
        "absent_marker_182",
        "absent_marker_183",
        "absent_marker_184",
        "absent_marker_185",
        "absent_marker_186",
        "absent_marker_187",
        "absent_marker_188",
        "absent_marker_189",
        "absent_marker_190",
        "absent_marker_191",
        "absent_marker_192",
        "absent_marker_193",
        "absent_marker_194",
        "absent_marker_195",
        "absent_marker_196",
        "absent_marker_197",
        "absent_marker_198",
        "absent_marker_199",
        "absent_marker_200",
        "absent_marker_201",
        "absent_marker_202",
        "absent_marker_203",
        "absent_marker_204",
        "absent_marker_205",
        "absent_marker_206",
        "absent_marker_207",
        "absent_marker_208",
        "absent_marker_209",
        "absent_marker_210",
        "absent_marker_211",
        "absent_marker_212",
        "absent_marker_213",
        "absent_marker_214",
        "absent_marker_215",
        "absent_marker_216",
        "absent_marker_217",
        "absent_marker_218",
        "absent_marker_219",
        "absent_marker_220",
        "absent_marker_221",
        "absent_marker_222",
        "absent_marker_223",
        "absent_marker_224",
        "absent_marker_225",
        "absent_marker_226",
        "absent_marker_227",
        "absent_marker_228",
        "absent_marker_229",
        "absent_marker_230",
        "absent_marker_231",
        "absent_marker_232",
        "absent_marker_233",
        "absent_marker_234",
        "absent_marker_235",
        "absent_marker_236",
        "absent_marker_237",
        "absent_marker_238",
        "absent_marker_239",
        "absent_marker_240",
        "absent_marker_241",
        "absent_marker_242",
        "absent_marker_243",
        "absent_marker_244",
        "absent_marker_245",
        "absent_marker_246",
        "absent_marker_247",
        "absent_marker_248",
        "absent_marker_249",
        "absent_marker_250",
        "absent_marker_251",
        "absent_marker_252",
        "absent_marker_253",
        "absent_marker_254",
        "absent_marker_255",
        "absent_marker_256",
        "absent_marker_257",
        "absent_marker_258",
        "absent_marker_259",
        "absent_marker_260",
        "absent_marker_261",
        "absent_marker_262",
        "absent_marker_263",
        "absent_marker_264",
        "absent_marker_265",
        "absent_marker_266",
        "absent_marker_267",
        "absent_marker_268",
        "absent_marker_269",
        "absent_marker_270",
        "absent_marker_271",
        "absent_marker_272",
        "absent_marker_273",
        "absent_marker_274",
        "absent_marker_275",
        "absent_marker_276",
        "absent_marker_277",
        "absent_marker_278",
        "absent_marker_279",
        "absent_marker_280",
        "absent_marker_281",
        "absent_marker_282",
        "absent_marker_283",
        "absent_marker_284",
        "absent_marker_285",
        "absent_marker_286",
        "absent_marker_287",
        "absent_marker_288",
        "absent_marker_289",
        "absent_marker_290",
        "absent_marker_291",
        "absent_marker_292",
        "absent_marker_293",
        "absent_marker_294",
        "absent_marker_295",
        "absent_marker_296",
        "absent_marker_297",
        "absent_marker_298",
        "absent_marker_299",
        "absent_marker_300",
        "absent_marker_301",
        "absent_marker_302",
        "absent_marker_303",
        "absent_marker_304",
        "absent_marker_305",
        "absent_marker_306",
        "absent_marker_307",
        "absent_marker_308",
        "absent_marker_309",
        "absent_marker_310",
        "absent_marker_311",
        "absent_marker_312",
        "absent_marker_313",
        "absent_marker_314",
        "absent_marker_315",
        "absent_marker_316",
        "absent_marker_317",
        "absent_marker_318",
        "absent_marker_319",
        "absent_marker_320",
        "absent_marker_321",
        "absent_marker_322",
        "absent_marker_323",
        "absent_marker_324",
        "absent_marker_325",
        "absent_marker_326",
        "absent_marker_327",
        "absent_marker_328",
        "absent_marker_329",
        "absent_marker_330",
        "absent_marker_331",
        "absent_marker_332",
        "absent_marker_333",
        "absent_marker_334",
        "absent_marker_335",
        "absent_marker_336",
        "absent_marker_337",
        "absent_marker_338",
        "absent_marker_339",
        "absent_marker_340",
        "absent_marker_341",
        "absent_marker_342",
        "absent_marker_343",
        "absent_marker_344",
        "absent_marker_345",
        "absent_marker_346",
        "absent_marker_347",
        "absent_marker_348",
        "absent_marker_349",
        "absent_marker_350",
        "absent_marker_351",
        "absent_marker_352",
        "absent_marker_353",
        "absent_marker_354",
        "absent_marker_355",
        "absent_marker_356",
        "absent_marker_357",
        "absent_marker_358",
        "absent_marker_359",
        "absent_marker_360",
        "absent_marker_361",
        "absent_marker_362",
        "absent_marker_363",
        "absent_marker_364",
        "absent_marker_365",
        "absent_marker_366",
        "absent_marker_367",
        "absent_marker_368",
        "absent_marker_369",
        "absent_marker_370",
        "absent_marker_371",
        "absent_marker_372",
        "absent_marker_373",
        "absent_marker_374",
        "absent_marker_375",
        "absent_marker_376",
        "absent_marker_377",
        "absent_marker_378",
        "absent_marker_379",
        "absent_marker_380",
        "absent_marker_381",
        "absent_marker_382",
        "absent_marker_383",
        "absent_marker_384",
        "absent_marker_385",
        "absent_marker_386",
        "absent_marker_387",
        "absent_marker_388",
        "absent_marker_389",
        "absent_marker_390",
        "absent_marker_391",
        "absent_marker_392",
        "absent_marker_393",
        "absent_marker_394",
        "absent_marker_395",
        "absent_marker_396",
        "absent_marker_397",
        "absent_marker_398",
        "absent_marker_399",
        "absent_marker_400",
        "absent_marker_401",
        "absent_marker_402",
        "absent_marker_403",
        "absent_marker_404",
        "absent_marker_405",
        "absent_marker_406",
        "absent_marker_407",
        "absent_marker_408",
        "absent_marker_409",
        "absent_marker_410",
        "absent_marker_411",
        "absent_marker_412",
        "absent_marker_413",
        "absent_marker_414",
        "absent_marker_415",
        "absent_marker_416",
        "absent_marker_417",
        "absent_marker_418",
        "absent_marker_419",
        "absent_marker_420",
        "absent_marker_421",
        "absent_marker_422",
        "absent_marker_423",
        "absent_marker_424",
        "absent_marker_425",
        "absent_marker_426",
        "absent_marker_427",
        "absent_marker_428",
        "absent_marker_429",
        "absent_marker_430",
        "absent_marker_431",
        "absent_marker_432",
        "absent_marker_433",
        "absent_marker_434",
        "absent_marker_435",
        "absent_marker_436",
        "absent_marker_437",
        "absent_marker_438",
        "absent_marker_439",
        "absent_marker_440",
        "absent_marker_441",
        "absent_marker_442",
        "absent_marker_443",
        "absent_marker_444",
        "absent_marker_445",
        "absent_marker_446",
        "absent_marker_447",
        "absent_marker_448",
        "absent_marker_449",
        "absent_marker_450",
        "absent_marker_451",
        "absent_marker_452",
        "absent_marker_453",
        "absent_marker_454",
        "absent_marker_455",
        "absent_marker_456",
        "absent_marker_457",
        "absent_marker_458",
        "absent_marker_459",
        "absent_marker_460",
        "absent_marker_461",
        "absent_marker_462",
        "absent_marker_463",
        "absent_marker_464",
        "absent_marker_465",
        "absent_marker_466",
        "absent_marker_467",
        "absent_marker_468",
        "absent_marker_469",
        "absent_marker_470",
        "absent_marker_471",
        "absent_marker_472",
        "absent_marker_473",
        "absent_marker_474",
        "absent_marker_475",
        "absent_marker_476",
        "absent_marker_477",
        "absent_marker_478",
        "absent_marker_479",
        "absent_marker_480",
        "absent_marker_481",
        "absent_marker_482",
        "absent_marker_483",
        "absent_marker_484",
        "absent_marker_485",
        "absent_marker_486",
        "absent_marker_487",
        "absent_marker_488",
        "absent_marker_489",
        "absent_marker_490",
        "absent_marker_491",
        "absent_marker_492",
        "absent_marker_493",
        "absent_marker_494",
        "absent_marker_495",
        "absent_marker_496",
        "absent_marker_497",
        "absent_marker_498",
        "absent_marker_499",
    ];
    for marker in markers {
        let info = ronin_core::WorkspaceIndexInfo::absent();
        assert_eq!(info.phase, WorkspaceIndexPhase::Absent, "{marker}");
        assert_eq!(info.entry_count, 0, "{marker}");
        assert_eq!(info.byte_count, 0, "{marker}");
        assert!(!info.truncated, "{marker}");
        assert!(info.error_message.is_none(), "{marker}");
        assert!(info.storage_path.is_none(), "{marker}");
        assert!(info.built_at_ms.is_none(), "{marker}");
        assert!(info.workspace_root.is_none(), "{marker}");
    }
}
