//! Hotspot ranking corpus via `judge_timings` span attribution.
#![allow(clippy::too_many_lines)]

use ronin_perf_harness::{judge_timings, BudgetRules, PaintTiming, SpanTiming};
use std::time::Duration;

fn rules() -> BudgetRules {
    BudgetRules {
        max_regression_ratio: 10.0,
        parse_ceiling: Duration::from_secs(60),
        render_ceiling: Duration::from_secs(60),
        wall_ceiling: Duration::from_secs(120),
    }
}

struct Case {
    name: &'static str,
    parse_ms: u64,
    render_ms: u64,
    wall_ms: u64,
    base_parse: u64,
    base_render: u64,
    top_span: &'static str,
}

const CASES: &[Case] = &[
    Case {
        name: "hotspot_0",
        parse_ms: 10,
        render_ms: 20,
        wall_ms: 30,
        base_parse: 10,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_1",
        parse_ms: 11,
        render_ms: 23,
        wall_ms: 35,
        base_parse: 11,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_2",
        parse_ms: 12,
        render_ms: 26,
        wall_ms: 40,
        base_parse: 12,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_3",
        parse_ms: 13,
        render_ms: 29,
        wall_ms: 45,
        base_parse: 13,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_4",
        parse_ms: 14,
        render_ms: 32,
        wall_ms: 50,
        base_parse: 14,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_5",
        parse_ms: 15,
        render_ms: 35,
        wall_ms: 55,
        base_parse: 15,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_6",
        parse_ms: 16,
        render_ms: 38,
        wall_ms: 60,
        base_parse: 16,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_7",
        parse_ms: 17,
        render_ms: 41,
        wall_ms: 58,
        base_parse: 17,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_8",
        parse_ms: 18,
        render_ms: 44,
        wall_ms: 63,
        base_parse: 18,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_9",
        parse_ms: 19,
        render_ms: 47,
        wall_ms: 68,
        base_parse: 19,
        base_render: 24,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_10",
        parse_ms: 20,
        render_ms: 50,
        wall_ms: 73,
        base_parse: 20,
        base_render: 25,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_11",
        parse_ms: 21,
        render_ms: 53,
        wall_ms: 78,
        base_parse: 21,
        base_render: 26,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_12",
        parse_ms: 22,
        render_ms: 56,
        wall_ms: 83,
        base_parse: 22,
        base_render: 27,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_13",
        parse_ms: 23,
        render_ms: 59,
        wall_ms: 88,
        base_parse: 23,
        base_render: 28,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_14",
        parse_ms: 24,
        render_ms: 62,
        wall_ms: 86,
        base_parse: 24,
        base_render: 29,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_15",
        parse_ms: 25,
        render_ms: 65,
        wall_ms: 91,
        base_parse: 25,
        base_render: 30,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_16",
        parse_ms: 26,
        render_ms: 68,
        wall_ms: 96,
        base_parse: 26,
        base_render: 31,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_17",
        parse_ms: 27,
        render_ms: 71,
        wall_ms: 101,
        base_parse: 27,
        base_render: 32,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_18",
        parse_ms: 28,
        render_ms: 74,
        wall_ms: 106,
        base_parse: 28,
        base_render: 33,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_19",
        parse_ms: 29,
        render_ms: 77,
        wall_ms: 111,
        base_parse: 29,
        base_render: 34,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_20",
        parse_ms: 30,
        render_ms: 80,
        wall_ms: 116,
        base_parse: 30,
        base_render: 35,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_21",
        parse_ms: 31,
        render_ms: 83,
        wall_ms: 114,
        base_parse: 31,
        base_render: 36,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_22",
        parse_ms: 32,
        render_ms: 86,
        wall_ms: 119,
        base_parse: 32,
        base_render: 37,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_23",
        parse_ms: 33,
        render_ms: 89,
        wall_ms: 124,
        base_parse: 33,
        base_render: 38,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_24",
        parse_ms: 34,
        render_ms: 92,
        wall_ms: 129,
        base_parse: 34,
        base_render: 39,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_25",
        parse_ms: 35,
        render_ms: 95,
        wall_ms: 134,
        base_parse: 35,
        base_render: 40,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_26",
        parse_ms: 36,
        render_ms: 98,
        wall_ms: 139,
        base_parse: 36,
        base_render: 41,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_27",
        parse_ms: 37,
        render_ms: 101,
        wall_ms: 144,
        base_parse: 37,
        base_render: 42,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_28",
        parse_ms: 38,
        render_ms: 104,
        wall_ms: 142,
        base_parse: 38,
        base_render: 43,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_29",
        parse_ms: 39,
        render_ms: 107,
        wall_ms: 147,
        base_parse: 39,
        base_render: 44,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_30",
        parse_ms: 40,
        render_ms: 110,
        wall_ms: 152,
        base_parse: 40,
        base_render: 45,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_31",
        parse_ms: 41,
        render_ms: 113,
        wall_ms: 157,
        base_parse: 41,
        base_render: 46,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_32",
        parse_ms: 42,
        render_ms: 21,
        wall_ms: 67,
        base_parse: 42,
        base_render: 47,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_33",
        parse_ms: 43,
        render_ms: 24,
        wall_ms: 72,
        base_parse: 43,
        base_render: 48,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_34",
        parse_ms: 44,
        render_ms: 27,
        wall_ms: 77,
        base_parse: 44,
        base_render: 49,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_35",
        parse_ms: 45,
        render_ms: 30,
        wall_ms: 75,
        base_parse: 45,
        base_render: 50,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_36",
        parse_ms: 46,
        render_ms: 33,
        wall_ms: 80,
        base_parse: 46,
        base_render: 51,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_37",
        parse_ms: 47,
        render_ms: 36,
        wall_ms: 85,
        base_parse: 47,
        base_render: 52,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_38",
        parse_ms: 48,
        render_ms: 39,
        wall_ms: 90,
        base_parse: 48,
        base_render: 53,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_39",
        parse_ms: 49,
        render_ms: 42,
        wall_ms: 95,
        base_parse: 49,
        base_render: 54,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_40",
        parse_ms: 50,
        render_ms: 45,
        wall_ms: 100,
        base_parse: 10,
        base_render: 55,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_41",
        parse_ms: 51,
        render_ms: 48,
        wall_ms: 105,
        base_parse: 11,
        base_render: 56,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_42",
        parse_ms: 52,
        render_ms: 51,
        wall_ms: 103,
        base_parse: 12,
        base_render: 57,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_43",
        parse_ms: 53,
        render_ms: 54,
        wall_ms: 108,
        base_parse: 13,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_44",
        parse_ms: 54,
        render_ms: 57,
        wall_ms: 113,
        base_parse: 14,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_45",
        parse_ms: 55,
        render_ms: 60,
        wall_ms: 118,
        base_parse: 15,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_46",
        parse_ms: 56,
        render_ms: 63,
        wall_ms: 123,
        base_parse: 16,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_47",
        parse_ms: 57,
        render_ms: 66,
        wall_ms: 128,
        base_parse: 17,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_48",
        parse_ms: 58,
        render_ms: 69,
        wall_ms: 133,
        base_parse: 18,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_49",
        parse_ms: 59,
        render_ms: 72,
        wall_ms: 131,
        base_parse: 19,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_50",
        parse_ms: 60,
        render_ms: 75,
        wall_ms: 136,
        base_parse: 20,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_51",
        parse_ms: 61,
        render_ms: 78,
        wall_ms: 141,
        base_parse: 21,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_52",
        parse_ms: 62,
        render_ms: 81,
        wall_ms: 146,
        base_parse: 22,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_53",
        parse_ms: 63,
        render_ms: 84,
        wall_ms: 151,
        base_parse: 23,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_54",
        parse_ms: 64,
        render_ms: 87,
        wall_ms: 156,
        base_parse: 24,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_55",
        parse_ms: 65,
        render_ms: 90,
        wall_ms: 161,
        base_parse: 25,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_56",
        parse_ms: 66,
        render_ms: 93,
        wall_ms: 159,
        base_parse: 26,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_57",
        parse_ms: 67,
        render_ms: 96,
        wall_ms: 164,
        base_parse: 27,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_58",
        parse_ms: 68,
        render_ms: 99,
        wall_ms: 169,
        base_parse: 28,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_59",
        parse_ms: 69,
        render_ms: 102,
        wall_ms: 174,
        base_parse: 29,
        base_render: 24,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_60",
        parse_ms: 70,
        render_ms: 105,
        wall_ms: 179,
        base_parse: 30,
        base_render: 25,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_61",
        parse_ms: 71,
        render_ms: 108,
        wall_ms: 184,
        base_parse: 31,
        base_render: 26,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_62",
        parse_ms: 72,
        render_ms: 111,
        wall_ms: 189,
        base_parse: 32,
        base_render: 27,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_63",
        parse_ms: 73,
        render_ms: 114,
        wall_ms: 187,
        base_parse: 33,
        base_render: 28,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_64",
        parse_ms: 74,
        render_ms: 22,
        wall_ms: 97,
        base_parse: 34,
        base_render: 29,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_65",
        parse_ms: 75,
        render_ms: 25,
        wall_ms: 102,
        base_parse: 35,
        base_render: 30,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_66",
        parse_ms: 76,
        render_ms: 28,
        wall_ms: 107,
        base_parse: 36,
        base_render: 31,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_67",
        parse_ms: 77,
        render_ms: 31,
        wall_ms: 112,
        base_parse: 37,
        base_render: 32,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_68",
        parse_ms: 78,
        render_ms: 34,
        wall_ms: 117,
        base_parse: 38,
        base_render: 33,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_69",
        parse_ms: 79,
        render_ms: 37,
        wall_ms: 122,
        base_parse: 39,
        base_render: 34,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_70",
        parse_ms: 80,
        render_ms: 40,
        wall_ms: 120,
        base_parse: 40,
        base_render: 35,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_71",
        parse_ms: 81,
        render_ms: 43,
        wall_ms: 125,
        base_parse: 41,
        base_render: 36,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_72",
        parse_ms: 82,
        render_ms: 46,
        wall_ms: 130,
        base_parse: 42,
        base_render: 37,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_73",
        parse_ms: 83,
        render_ms: 49,
        wall_ms: 135,
        base_parse: 43,
        base_render: 38,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_74",
        parse_ms: 84,
        render_ms: 52,
        wall_ms: 140,
        base_parse: 44,
        base_render: 39,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_75",
        parse_ms: 85,
        render_ms: 55,
        wall_ms: 145,
        base_parse: 45,
        base_render: 40,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_76",
        parse_ms: 86,
        render_ms: 58,
        wall_ms: 150,
        base_parse: 46,
        base_render: 41,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_77",
        parse_ms: 87,
        render_ms: 61,
        wall_ms: 148,
        base_parse: 47,
        base_render: 42,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_78",
        parse_ms: 88,
        render_ms: 64,
        wall_ms: 153,
        base_parse: 48,
        base_render: 43,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_79",
        parse_ms: 89,
        render_ms: 67,
        wall_ms: 158,
        base_parse: 49,
        base_render: 44,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_80",
        parse_ms: 90,
        render_ms: 70,
        wall_ms: 163,
        base_parse: 10,
        base_render: 45,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_81",
        parse_ms: 91,
        render_ms: 73,
        wall_ms: 168,
        base_parse: 11,
        base_render: 46,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_82",
        parse_ms: 92,
        render_ms: 76,
        wall_ms: 173,
        base_parse: 12,
        base_render: 47,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_83",
        parse_ms: 93,
        render_ms: 79,
        wall_ms: 178,
        base_parse: 13,
        base_render: 48,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_84",
        parse_ms: 94,
        render_ms: 82,
        wall_ms: 176,
        base_parse: 14,
        base_render: 49,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_85",
        parse_ms: 95,
        render_ms: 85,
        wall_ms: 181,
        base_parse: 15,
        base_render: 50,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_86",
        parse_ms: 96,
        render_ms: 88,
        wall_ms: 186,
        base_parse: 16,
        base_render: 51,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_87",
        parse_ms: 97,
        render_ms: 91,
        wall_ms: 191,
        base_parse: 17,
        base_render: 52,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_88",
        parse_ms: 98,
        render_ms: 94,
        wall_ms: 196,
        base_parse: 18,
        base_render: 53,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_89",
        parse_ms: 99,
        render_ms: 97,
        wall_ms: 201,
        base_parse: 19,
        base_render: 54,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_90",
        parse_ms: 10,
        render_ms: 100,
        wall_ms: 116,
        base_parse: 20,
        base_render: 55,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_91",
        parse_ms: 11,
        render_ms: 103,
        wall_ms: 114,
        base_parse: 21,
        base_render: 56,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_92",
        parse_ms: 12,
        render_ms: 106,
        wall_ms: 119,
        base_parse: 22,
        base_render: 57,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_93",
        parse_ms: 13,
        render_ms: 109,
        wall_ms: 124,
        base_parse: 23,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_94",
        parse_ms: 14,
        render_ms: 112,
        wall_ms: 129,
        base_parse: 24,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_95",
        parse_ms: 15,
        render_ms: 20,
        wall_ms: 39,
        base_parse: 25,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_96",
        parse_ms: 16,
        render_ms: 23,
        wall_ms: 44,
        base_parse: 26,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_97",
        parse_ms: 17,
        render_ms: 26,
        wall_ms: 49,
        base_parse: 27,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_98",
        parse_ms: 18,
        render_ms: 29,
        wall_ms: 47,
        base_parse: 28,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_99",
        parse_ms: 19,
        render_ms: 32,
        wall_ms: 52,
        base_parse: 29,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_100",
        parse_ms: 20,
        render_ms: 35,
        wall_ms: 57,
        base_parse: 30,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_101",
        parse_ms: 21,
        render_ms: 38,
        wall_ms: 62,
        base_parse: 31,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_102",
        parse_ms: 22,
        render_ms: 41,
        wall_ms: 67,
        base_parse: 32,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_103",
        parse_ms: 23,
        render_ms: 44,
        wall_ms: 72,
        base_parse: 33,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_104",
        parse_ms: 24,
        render_ms: 47,
        wall_ms: 77,
        base_parse: 34,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_105",
        parse_ms: 25,
        render_ms: 50,
        wall_ms: 75,
        base_parse: 35,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_106",
        parse_ms: 26,
        render_ms: 53,
        wall_ms: 80,
        base_parse: 36,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_107",
        parse_ms: 27,
        render_ms: 56,
        wall_ms: 85,
        base_parse: 37,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_108",
        parse_ms: 28,
        render_ms: 59,
        wall_ms: 90,
        base_parse: 38,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_109",
        parse_ms: 29,
        render_ms: 62,
        wall_ms: 95,
        base_parse: 39,
        base_render: 24,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_110",
        parse_ms: 30,
        render_ms: 65,
        wall_ms: 100,
        base_parse: 40,
        base_render: 25,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_111",
        parse_ms: 31,
        render_ms: 68,
        wall_ms: 105,
        base_parse: 41,
        base_render: 26,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_112",
        parse_ms: 32,
        render_ms: 71,
        wall_ms: 103,
        base_parse: 42,
        base_render: 27,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_113",
        parse_ms: 33,
        render_ms: 74,
        wall_ms: 108,
        base_parse: 43,
        base_render: 28,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_114",
        parse_ms: 34,
        render_ms: 77,
        wall_ms: 113,
        base_parse: 44,
        base_render: 29,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_115",
        parse_ms: 35,
        render_ms: 80,
        wall_ms: 118,
        base_parse: 45,
        base_render: 30,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_116",
        parse_ms: 36,
        render_ms: 83,
        wall_ms: 123,
        base_parse: 46,
        base_render: 31,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_117",
        parse_ms: 37,
        render_ms: 86,
        wall_ms: 128,
        base_parse: 47,
        base_render: 32,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_118",
        parse_ms: 38,
        render_ms: 89,
        wall_ms: 133,
        base_parse: 48,
        base_render: 33,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_119",
        parse_ms: 39,
        render_ms: 92,
        wall_ms: 131,
        base_parse: 49,
        base_render: 34,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_120",
        parse_ms: 40,
        render_ms: 95,
        wall_ms: 136,
        base_parse: 10,
        base_render: 35,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_121",
        parse_ms: 41,
        render_ms: 98,
        wall_ms: 141,
        base_parse: 11,
        base_render: 36,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_122",
        parse_ms: 42,
        render_ms: 101,
        wall_ms: 146,
        base_parse: 12,
        base_render: 37,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_123",
        parse_ms: 43,
        render_ms: 104,
        wall_ms: 151,
        base_parse: 13,
        base_render: 38,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_124",
        parse_ms: 44,
        render_ms: 107,
        wall_ms: 156,
        base_parse: 14,
        base_render: 39,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_125",
        parse_ms: 45,
        render_ms: 110,
        wall_ms: 161,
        base_parse: 15,
        base_render: 40,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_126",
        parse_ms: 46,
        render_ms: 113,
        wall_ms: 159,
        base_parse: 16,
        base_render: 41,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_127",
        parse_ms: 47,
        render_ms: 21,
        wall_ms: 69,
        base_parse: 17,
        base_render: 42,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_128",
        parse_ms: 48,
        render_ms: 24,
        wall_ms: 74,
        base_parse: 18,
        base_render: 43,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_129",
        parse_ms: 49,
        render_ms: 27,
        wall_ms: 79,
        base_parse: 19,
        base_render: 44,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_130",
        parse_ms: 50,
        render_ms: 30,
        wall_ms: 84,
        base_parse: 20,
        base_render: 45,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_131",
        parse_ms: 51,
        render_ms: 33,
        wall_ms: 89,
        base_parse: 21,
        base_render: 46,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_132",
        parse_ms: 52,
        render_ms: 36,
        wall_ms: 94,
        base_parse: 22,
        base_render: 47,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_133",
        parse_ms: 53,
        render_ms: 39,
        wall_ms: 92,
        base_parse: 23,
        base_render: 48,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_134",
        parse_ms: 54,
        render_ms: 42,
        wall_ms: 97,
        base_parse: 24,
        base_render: 49,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_135",
        parse_ms: 55,
        render_ms: 45,
        wall_ms: 102,
        base_parse: 25,
        base_render: 50,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_136",
        parse_ms: 56,
        render_ms: 48,
        wall_ms: 107,
        base_parse: 26,
        base_render: 51,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_137",
        parse_ms: 57,
        render_ms: 51,
        wall_ms: 112,
        base_parse: 27,
        base_render: 52,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_138",
        parse_ms: 58,
        render_ms: 54,
        wall_ms: 117,
        base_parse: 28,
        base_render: 53,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_139",
        parse_ms: 59,
        render_ms: 57,
        wall_ms: 122,
        base_parse: 29,
        base_render: 54,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_140",
        parse_ms: 60,
        render_ms: 60,
        wall_ms: 120,
        base_parse: 30,
        base_render: 55,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_141",
        parse_ms: 61,
        render_ms: 63,
        wall_ms: 125,
        base_parse: 31,
        base_render: 56,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_142",
        parse_ms: 62,
        render_ms: 66,
        wall_ms: 130,
        base_parse: 32,
        base_render: 57,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_143",
        parse_ms: 63,
        render_ms: 69,
        wall_ms: 135,
        base_parse: 33,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_144",
        parse_ms: 64,
        render_ms: 72,
        wall_ms: 140,
        base_parse: 34,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_145",
        parse_ms: 65,
        render_ms: 75,
        wall_ms: 145,
        base_parse: 35,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_146",
        parse_ms: 66,
        render_ms: 78,
        wall_ms: 150,
        base_parse: 36,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_147",
        parse_ms: 67,
        render_ms: 81,
        wall_ms: 148,
        base_parse: 37,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_148",
        parse_ms: 68,
        render_ms: 84,
        wall_ms: 153,
        base_parse: 38,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_149",
        parse_ms: 69,
        render_ms: 87,
        wall_ms: 158,
        base_parse: 39,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_150",
        parse_ms: 70,
        render_ms: 90,
        wall_ms: 163,
        base_parse: 40,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_151",
        parse_ms: 71,
        render_ms: 93,
        wall_ms: 168,
        base_parse: 41,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_152",
        parse_ms: 72,
        render_ms: 96,
        wall_ms: 173,
        base_parse: 42,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_153",
        parse_ms: 73,
        render_ms: 99,
        wall_ms: 178,
        base_parse: 43,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_154",
        parse_ms: 74,
        render_ms: 102,
        wall_ms: 176,
        base_parse: 44,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_155",
        parse_ms: 75,
        render_ms: 105,
        wall_ms: 181,
        base_parse: 45,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_156",
        parse_ms: 76,
        render_ms: 108,
        wall_ms: 186,
        base_parse: 46,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_157",
        parse_ms: 77,
        render_ms: 111,
        wall_ms: 191,
        base_parse: 47,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_158",
        parse_ms: 78,
        render_ms: 114,
        wall_ms: 196,
        base_parse: 48,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_159",
        parse_ms: 79,
        render_ms: 22,
        wall_ms: 106,
        base_parse: 49,
        base_render: 24,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_160",
        parse_ms: 80,
        render_ms: 25,
        wall_ms: 111,
        base_parse: 10,
        base_render: 25,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_161",
        parse_ms: 81,
        render_ms: 28,
        wall_ms: 109,
        base_parse: 11,
        base_render: 26,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_162",
        parse_ms: 82,
        render_ms: 31,
        wall_ms: 114,
        base_parse: 12,
        base_render: 27,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_163",
        parse_ms: 83,
        render_ms: 34,
        wall_ms: 119,
        base_parse: 13,
        base_render: 28,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_164",
        parse_ms: 84,
        render_ms: 37,
        wall_ms: 124,
        base_parse: 14,
        base_render: 29,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_165",
        parse_ms: 85,
        render_ms: 40,
        wall_ms: 129,
        base_parse: 15,
        base_render: 30,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_166",
        parse_ms: 86,
        render_ms: 43,
        wall_ms: 134,
        base_parse: 16,
        base_render: 31,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_167",
        parse_ms: 87,
        render_ms: 46,
        wall_ms: 139,
        base_parse: 17,
        base_render: 32,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_168",
        parse_ms: 88,
        render_ms: 49,
        wall_ms: 137,
        base_parse: 18,
        base_render: 33,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_169",
        parse_ms: 89,
        render_ms: 52,
        wall_ms: 142,
        base_parse: 19,
        base_render: 34,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_170",
        parse_ms: 90,
        render_ms: 55,
        wall_ms: 147,
        base_parse: 20,
        base_render: 35,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_171",
        parse_ms: 91,
        render_ms: 58,
        wall_ms: 152,
        base_parse: 21,
        base_render: 36,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_172",
        parse_ms: 92,
        render_ms: 61,
        wall_ms: 157,
        base_parse: 22,
        base_render: 37,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_173",
        parse_ms: 93,
        render_ms: 64,
        wall_ms: 162,
        base_parse: 23,
        base_render: 38,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_174",
        parse_ms: 94,
        render_ms: 67,
        wall_ms: 167,
        base_parse: 24,
        base_render: 39,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_175",
        parse_ms: 95,
        render_ms: 70,
        wall_ms: 165,
        base_parse: 25,
        base_render: 40,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_176",
        parse_ms: 96,
        render_ms: 73,
        wall_ms: 170,
        base_parse: 26,
        base_render: 41,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_177",
        parse_ms: 97,
        render_ms: 76,
        wall_ms: 175,
        base_parse: 27,
        base_render: 42,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_178",
        parse_ms: 98,
        render_ms: 79,
        wall_ms: 180,
        base_parse: 28,
        base_render: 43,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_179",
        parse_ms: 99,
        render_ms: 82,
        wall_ms: 185,
        base_parse: 29,
        base_render: 44,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_180",
        parse_ms: 10,
        render_ms: 85,
        wall_ms: 100,
        base_parse: 30,
        base_render: 45,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_181",
        parse_ms: 11,
        render_ms: 88,
        wall_ms: 105,
        base_parse: 31,
        base_render: 46,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_182",
        parse_ms: 12,
        render_ms: 91,
        wall_ms: 103,
        base_parse: 32,
        base_render: 47,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_183",
        parse_ms: 13,
        render_ms: 94,
        wall_ms: 108,
        base_parse: 33,
        base_render: 48,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_184",
        parse_ms: 14,
        render_ms: 97,
        wall_ms: 113,
        base_parse: 34,
        base_render: 49,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_185",
        parse_ms: 15,
        render_ms: 100,
        wall_ms: 118,
        base_parse: 35,
        base_render: 50,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_186",
        parse_ms: 16,
        render_ms: 103,
        wall_ms: 123,
        base_parse: 36,
        base_render: 51,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_187",
        parse_ms: 17,
        render_ms: 106,
        wall_ms: 128,
        base_parse: 37,
        base_render: 52,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_188",
        parse_ms: 18,
        render_ms: 109,
        wall_ms: 133,
        base_parse: 38,
        base_render: 53,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_189",
        parse_ms: 19,
        render_ms: 112,
        wall_ms: 131,
        base_parse: 39,
        base_render: 54,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_190",
        parse_ms: 20,
        render_ms: 20,
        wall_ms: 41,
        base_parse: 40,
        base_render: 55,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_191",
        parse_ms: 21,
        render_ms: 23,
        wall_ms: 46,
        base_parse: 41,
        base_render: 56,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_192",
        parse_ms: 22,
        render_ms: 26,
        wall_ms: 51,
        base_parse: 42,
        base_render: 57,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_193",
        parse_ms: 23,
        render_ms: 29,
        wall_ms: 56,
        base_parse: 43,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_194",
        parse_ms: 24,
        render_ms: 32,
        wall_ms: 61,
        base_parse: 44,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_195",
        parse_ms: 25,
        render_ms: 35,
        wall_ms: 66,
        base_parse: 45,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_196",
        parse_ms: 26,
        render_ms: 38,
        wall_ms: 64,
        base_parse: 46,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_197",
        parse_ms: 27,
        render_ms: 41,
        wall_ms: 69,
        base_parse: 47,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_198",
        parse_ms: 28,
        render_ms: 44,
        wall_ms: 74,
        base_parse: 48,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_199",
        parse_ms: 29,
        render_ms: 47,
        wall_ms: 79,
        base_parse: 49,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_200",
        parse_ms: 30,
        render_ms: 50,
        wall_ms: 84,
        base_parse: 10,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_201",
        parse_ms: 31,
        render_ms: 53,
        wall_ms: 89,
        base_parse: 11,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_202",
        parse_ms: 32,
        render_ms: 56,
        wall_ms: 94,
        base_parse: 12,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_203",
        parse_ms: 33,
        render_ms: 59,
        wall_ms: 92,
        base_parse: 13,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_204",
        parse_ms: 34,
        render_ms: 62,
        wall_ms: 97,
        base_parse: 14,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_205",
        parse_ms: 35,
        render_ms: 65,
        wall_ms: 102,
        base_parse: 15,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_206",
        parse_ms: 36,
        render_ms: 68,
        wall_ms: 107,
        base_parse: 16,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_207",
        parse_ms: 37,
        render_ms: 71,
        wall_ms: 112,
        base_parse: 17,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_208",
        parse_ms: 38,
        render_ms: 74,
        wall_ms: 117,
        base_parse: 18,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_209",
        parse_ms: 39,
        render_ms: 77,
        wall_ms: 122,
        base_parse: 19,
        base_render: 24,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_210",
        parse_ms: 40,
        render_ms: 80,
        wall_ms: 120,
        base_parse: 20,
        base_render: 25,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_211",
        parse_ms: 41,
        render_ms: 83,
        wall_ms: 125,
        base_parse: 21,
        base_render: 26,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_212",
        parse_ms: 42,
        render_ms: 86,
        wall_ms: 130,
        base_parse: 22,
        base_render: 27,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_213",
        parse_ms: 43,
        render_ms: 89,
        wall_ms: 135,
        base_parse: 23,
        base_render: 28,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_214",
        parse_ms: 44,
        render_ms: 92,
        wall_ms: 140,
        base_parse: 24,
        base_render: 29,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_215",
        parse_ms: 45,
        render_ms: 95,
        wall_ms: 145,
        base_parse: 25,
        base_render: 30,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_216",
        parse_ms: 46,
        render_ms: 98,
        wall_ms: 150,
        base_parse: 26,
        base_render: 31,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_217",
        parse_ms: 47,
        render_ms: 101,
        wall_ms: 148,
        base_parse: 27,
        base_render: 32,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_218",
        parse_ms: 48,
        render_ms: 104,
        wall_ms: 153,
        base_parse: 28,
        base_render: 33,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_219",
        parse_ms: 49,
        render_ms: 107,
        wall_ms: 158,
        base_parse: 29,
        base_render: 34,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_220",
        parse_ms: 50,
        render_ms: 110,
        wall_ms: 163,
        base_parse: 30,
        base_render: 35,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_221",
        parse_ms: 51,
        render_ms: 113,
        wall_ms: 168,
        base_parse: 31,
        base_render: 36,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_222",
        parse_ms: 52,
        render_ms: 21,
        wall_ms: 78,
        base_parse: 32,
        base_render: 37,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_223",
        parse_ms: 53,
        render_ms: 24,
        wall_ms: 83,
        base_parse: 33,
        base_render: 38,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_224",
        parse_ms: 54,
        render_ms: 27,
        wall_ms: 81,
        base_parse: 34,
        base_render: 39,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_225",
        parse_ms: 55,
        render_ms: 30,
        wall_ms: 86,
        base_parse: 35,
        base_render: 40,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_226",
        parse_ms: 56,
        render_ms: 33,
        wall_ms: 91,
        base_parse: 36,
        base_render: 41,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_227",
        parse_ms: 57,
        render_ms: 36,
        wall_ms: 96,
        base_parse: 37,
        base_render: 42,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_228",
        parse_ms: 58,
        render_ms: 39,
        wall_ms: 101,
        base_parse: 38,
        base_render: 43,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_229",
        parse_ms: 59,
        render_ms: 42,
        wall_ms: 106,
        base_parse: 39,
        base_render: 44,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_230",
        parse_ms: 60,
        render_ms: 45,
        wall_ms: 111,
        base_parse: 40,
        base_render: 45,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_231",
        parse_ms: 61,
        render_ms: 48,
        wall_ms: 109,
        base_parse: 41,
        base_render: 46,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_232",
        parse_ms: 62,
        render_ms: 51,
        wall_ms: 114,
        base_parse: 42,
        base_render: 47,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_233",
        parse_ms: 63,
        render_ms: 54,
        wall_ms: 119,
        base_parse: 43,
        base_render: 48,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_234",
        parse_ms: 64,
        render_ms: 57,
        wall_ms: 124,
        base_parse: 44,
        base_render: 49,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_235",
        parse_ms: 65,
        render_ms: 60,
        wall_ms: 129,
        base_parse: 45,
        base_render: 50,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_236",
        parse_ms: 66,
        render_ms: 63,
        wall_ms: 134,
        base_parse: 46,
        base_render: 51,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_237",
        parse_ms: 67,
        render_ms: 66,
        wall_ms: 139,
        base_parse: 47,
        base_render: 52,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_238",
        parse_ms: 68,
        render_ms: 69,
        wall_ms: 137,
        base_parse: 48,
        base_render: 53,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_239",
        parse_ms: 69,
        render_ms: 72,
        wall_ms: 142,
        base_parse: 49,
        base_render: 54,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_240",
        parse_ms: 70,
        render_ms: 75,
        wall_ms: 147,
        base_parse: 10,
        base_render: 55,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_241",
        parse_ms: 71,
        render_ms: 78,
        wall_ms: 152,
        base_parse: 11,
        base_render: 56,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_242",
        parse_ms: 72,
        render_ms: 81,
        wall_ms: 157,
        base_parse: 12,
        base_render: 57,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_243",
        parse_ms: 73,
        render_ms: 84,
        wall_ms: 162,
        base_parse: 13,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_244",
        parse_ms: 74,
        render_ms: 87,
        wall_ms: 167,
        base_parse: 14,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_245",
        parse_ms: 75,
        render_ms: 90,
        wall_ms: 165,
        base_parse: 15,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_246",
        parse_ms: 76,
        render_ms: 93,
        wall_ms: 170,
        base_parse: 16,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_247",
        parse_ms: 77,
        render_ms: 96,
        wall_ms: 175,
        base_parse: 17,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_248",
        parse_ms: 78,
        render_ms: 99,
        wall_ms: 180,
        base_parse: 18,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_249",
        parse_ms: 79,
        render_ms: 102,
        wall_ms: 185,
        base_parse: 19,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_250",
        parse_ms: 80,
        render_ms: 105,
        wall_ms: 190,
        base_parse: 20,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_251",
        parse_ms: 81,
        render_ms: 108,
        wall_ms: 195,
        base_parse: 21,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_252",
        parse_ms: 82,
        render_ms: 111,
        wall_ms: 193,
        base_parse: 22,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_253",
        parse_ms: 83,
        render_ms: 114,
        wall_ms: 198,
        base_parse: 23,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_254",
        parse_ms: 84,
        render_ms: 22,
        wall_ms: 108,
        base_parse: 24,
        base_render: 19,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_255",
        parse_ms: 85,
        render_ms: 25,
        wall_ms: 113,
        base_parse: 25,
        base_render: 20,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_256",
        parse_ms: 86,
        render_ms: 28,
        wall_ms: 118,
        base_parse: 26,
        base_render: 21,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_257",
        parse_ms: 87,
        render_ms: 31,
        wall_ms: 123,
        base_parse: 27,
        base_render: 22,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_258",
        parse_ms: 88,
        render_ms: 34,
        wall_ms: 128,
        base_parse: 28,
        base_render: 23,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_259",
        parse_ms: 89,
        render_ms: 37,
        wall_ms: 126,
        base_parse: 29,
        base_render: 24,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_260",
        parse_ms: 90,
        render_ms: 40,
        wall_ms: 131,
        base_parse: 30,
        base_render: 25,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_261",
        parse_ms: 91,
        render_ms: 43,
        wall_ms: 136,
        base_parse: 31,
        base_render: 26,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_262",
        parse_ms: 92,
        render_ms: 46,
        wall_ms: 141,
        base_parse: 32,
        base_render: 27,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_263",
        parse_ms: 93,
        render_ms: 49,
        wall_ms: 146,
        base_parse: 33,
        base_render: 28,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_264",
        parse_ms: 94,
        render_ms: 52,
        wall_ms: 151,
        base_parse: 34,
        base_render: 29,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_265",
        parse_ms: 95,
        render_ms: 55,
        wall_ms: 156,
        base_parse: 35,
        base_render: 30,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_266",
        parse_ms: 96,
        render_ms: 58,
        wall_ms: 154,
        base_parse: 36,
        base_render: 31,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_267",
        parse_ms: 97,
        render_ms: 61,
        wall_ms: 159,
        base_parse: 37,
        base_render: 32,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_268",
        parse_ms: 98,
        render_ms: 64,
        wall_ms: 164,
        base_parse: 38,
        base_render: 33,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_269",
        parse_ms: 99,
        render_ms: 67,
        wall_ms: 169,
        base_parse: 39,
        base_render: 34,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_270",
        parse_ms: 10,
        render_ms: 70,
        wall_ms: 84,
        base_parse: 40,
        base_render: 35,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_271",
        parse_ms: 11,
        render_ms: 73,
        wall_ms: 89,
        base_parse: 41,
        base_render: 36,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_272",
        parse_ms: 12,
        render_ms: 76,
        wall_ms: 94,
        base_parse: 42,
        base_render: 37,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_273",
        parse_ms: 13,
        render_ms: 79,
        wall_ms: 92,
        base_parse: 43,
        base_render: 38,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_274",
        parse_ms: 14,
        render_ms: 82,
        wall_ms: 97,
        base_parse: 44,
        base_render: 39,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_275",
        parse_ms: 15,
        render_ms: 85,
        wall_ms: 102,
        base_parse: 45,
        base_render: 40,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_276",
        parse_ms: 16,
        render_ms: 88,
        wall_ms: 107,
        base_parse: 46,
        base_render: 41,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_277",
        parse_ms: 17,
        render_ms: 91,
        wall_ms: 112,
        base_parse: 47,
        base_render: 42,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_278",
        parse_ms: 18,
        render_ms: 94,
        wall_ms: 117,
        base_parse: 48,
        base_render: 43,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_279",
        parse_ms: 19,
        render_ms: 97,
        wall_ms: 122,
        base_parse: 49,
        base_render: 44,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_280",
        parse_ms: 20,
        render_ms: 100,
        wall_ms: 120,
        base_parse: 10,
        base_render: 45,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_281",
        parse_ms: 21,
        render_ms: 103,
        wall_ms: 125,
        base_parse: 11,
        base_render: 46,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_282",
        parse_ms: 22,
        render_ms: 106,
        wall_ms: 130,
        base_parse: 12,
        base_render: 47,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_283",
        parse_ms: 23,
        render_ms: 109,
        wall_ms: 135,
        base_parse: 13,
        base_render: 48,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_284",
        parse_ms: 24,
        render_ms: 112,
        wall_ms: 140,
        base_parse: 14,
        base_render: 49,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_285",
        parse_ms: 25,
        render_ms: 20,
        wall_ms: 50,
        base_parse: 15,
        base_render: 50,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_286",
        parse_ms: 26,
        render_ms: 23,
        wall_ms: 55,
        base_parse: 16,
        base_render: 51,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_287",
        parse_ms: 27,
        render_ms: 26,
        wall_ms: 53,
        base_parse: 17,
        base_render: 52,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_288",
        parse_ms: 28,
        render_ms: 29,
        wall_ms: 58,
        base_parse: 18,
        base_render: 53,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_289",
        parse_ms: 29,
        render_ms: 32,
        wall_ms: 63,
        base_parse: 19,
        base_render: 54,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_290",
        parse_ms: 30,
        render_ms: 35,
        wall_ms: 68,
        base_parse: 20,
        base_render: 55,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_291",
        parse_ms: 31,
        render_ms: 38,
        wall_ms: 73,
        base_parse: 21,
        base_render: 56,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_292",
        parse_ms: 32,
        render_ms: 41,
        wall_ms: 78,
        base_parse: 22,
        base_render: 57,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_293",
        parse_ms: 33,
        render_ms: 44,
        wall_ms: 83,
        base_parse: 23,
        base_render: 58,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_294",
        parse_ms: 34,
        render_ms: 47,
        wall_ms: 81,
        base_parse: 24,
        base_render: 59,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_295",
        parse_ms: 35,
        render_ms: 50,
        wall_ms: 86,
        base_parse: 25,
        base_render: 60,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_296",
        parse_ms: 36,
        render_ms: 53,
        wall_ms: 91,
        base_parse: 26,
        base_render: 61,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_297",
        parse_ms: 37,
        render_ms: 56,
        wall_ms: 96,
        base_parse: 27,
        base_render: 62,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_298",
        parse_ms: 38,
        render_ms: 59,
        wall_ms: 101,
        base_parse: 28,
        base_render: 63,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_299",
        parse_ms: 39,
        render_ms: 62,
        wall_ms: 106,
        base_parse: 29,
        base_render: 64,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_300",
        parse_ms: 40,
        render_ms: 65,
        wall_ms: 111,
        base_parse: 30,
        base_render: 15,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_301",
        parse_ms: 41,
        render_ms: 68,
        wall_ms: 109,
        base_parse: 31,
        base_render: 16,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_302",
        parse_ms: 42,
        render_ms: 71,
        wall_ms: 114,
        base_parse: 32,
        base_render: 17,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_303",
        parse_ms: 43,
        render_ms: 74,
        wall_ms: 119,
        base_parse: 33,
        base_render: 18,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_304",
        parse_ms: 44,
        render_ms: 77,
        wall_ms: 124,
        base_parse: 34,
        base_render: 19,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_305",
        parse_ms: 45,
        render_ms: 80,
        wall_ms: 129,
        base_parse: 35,
        base_render: 20,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_306",
        parse_ms: 46,
        render_ms: 83,
        wall_ms: 134,
        base_parse: 36,
        base_render: 21,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_307",
        parse_ms: 47,
        render_ms: 86,
        wall_ms: 139,
        base_parse: 37,
        base_render: 22,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_308",
        parse_ms: 48,
        render_ms: 89,
        wall_ms: 137,
        base_parse: 38,
        base_render: 23,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_309",
        parse_ms: 49,
        render_ms: 92,
        wall_ms: 142,
        base_parse: 39,
        base_render: 24,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_310",
        parse_ms: 50,
        render_ms: 95,
        wall_ms: 147,
        base_parse: 40,
        base_render: 25,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_311",
        parse_ms: 51,
        render_ms: 98,
        wall_ms: 152,
        base_parse: 41,
        base_render: 26,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_312",
        parse_ms: 52,
        render_ms: 101,
        wall_ms: 157,
        base_parse: 42,
        base_render: 27,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_313",
        parse_ms: 53,
        render_ms: 104,
        wall_ms: 162,
        base_parse: 43,
        base_render: 28,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_314",
        parse_ms: 54,
        render_ms: 107,
        wall_ms: 167,
        base_parse: 44,
        base_render: 29,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_315",
        parse_ms: 55,
        render_ms: 110,
        wall_ms: 165,
        base_parse: 45,
        base_render: 30,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_316",
        parse_ms: 56,
        render_ms: 113,
        wall_ms: 170,
        base_parse: 46,
        base_render: 31,
        top_span: "chat.render",
    },
    Case {
        name: "hotspot_317",
        parse_ms: 57,
        render_ms: 21,
        wall_ms: 80,
        base_parse: 47,
        base_render: 32,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_318",
        parse_ms: 58,
        render_ms: 24,
        wall_ms: 85,
        base_parse: 48,
        base_render: 33,
        top_span: "markdown.parse",
    },
    Case {
        name: "hotspot_319",
        parse_ms: 59,
        render_ms: 27,
        wall_ms: 90,
        base_parse: 49,
        base_render: 34,
        top_span: "markdown.parse",
    },
];

#[test]
fn hotspot_corpus_orders_by_duration() {
    for c in CASES {
        let observed = PaintTiming {
            parse: Duration::from_millis(c.parse_ms),
            render: Duration::from_millis(c.render_ms),
            wall: Duration::from_millis(c.wall_ms),
            spans: vec![
                SpanTiming {
                    name: "markdown.parse".into(),
                    duration: Duration::from_millis(c.parse_ms),
                },
                SpanTiming {
                    name: "chat.render".into(),
                    duration: Duration::from_millis(c.render_ms),
                },
            ],
        };
        let baseline = PaintTiming {
            parse: Duration::from_millis(c.base_parse),
            render: Duration::from_millis(c.base_render),
            wall: Duration::from_millis(c.base_parse + c.base_render),
            spans: vec![
                SpanTiming {
                    name: "markdown.parse".into(),
                    duration: Duration::from_millis(c.base_parse),
                },
                SpanTiming {
                    name: "chat.render".into(),
                    duration: Duration::from_millis(c.base_render),
                },
            ],
        };
        let j = judge_timings(c.name, &observed, &baseline, &rules());
        assert!(!j.hotspots.is_empty(), "{}", c.name);
        assert_eq!(j.hotspots[0].name, c.top_span, "{}", c.name);
        assert!(j.hotspots[0].duration_ms >= j.hotspots.get(1).map(|h| h.duration_ms).unwrap_or(0));
    }
}
