//! Core domain types shared across Ronin crates.

use std::path::PathBuf;

use ronin_db::{DbArtifact, DbAttachment, DbMemory, DbMessage, DbThread};

/// Filesystem locations used by a Ronin app session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RoninPaths {
    /// Directory for user-editable or generated configuration files.
    pub config_dir: PathBuf,
    /// Directory for local application data such as `ronin.db`.
    pub data_dir: PathBuf,
}

/// User-visible conversation thread metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Thread {
    /// App-generated opaque thread identifier.
    pub id: String,
    /// User-visible title. New M0 threads start as `New Chat`.
    pub title: String,
    /// Creation timestamp as UTC Unix milliseconds.
    pub created_at: i64,
    /// Last update timestamp as UTC Unix milliseconds.
    pub updated_at: i64,
    /// Whether the thread is archived. M0 stores this but has no UI for it yet.
    pub archived: bool,
    /// Opaque identifier for the AI provider (e.g. "ollama", "openai").
    pub provider: Option<String>,
    /// Selected model name.
    pub model: Option<String>,
}

/// Role of a chat message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MessageRole {
    /// Message sent by the user.
    User,
    /// Response generated by the assistant.
    Assistant,
    /// System-level instruction (not persisted).
    System,
}

/// Lifecycle status of an assistant message.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MessageStatus {
    /// Message is fully written and complete.
    Complete,
    /// Message is being generated; content may be partial.
    Streaming,
    /// Generation failed or was cancelled.
    Error,
    /// User cancelled the generation.
    Cancelled,
    /// Generation was interrupted before completion (e.g. app exited).
    Failed,
}

/// A chat message within a thread.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Message {
    /// App-generated opaque message identifier.
    pub id: String,
    /// Owning thread identifier.
    pub thread_id: String,
    /// Message role.
    pub role: MessageRole,
    /// Message body content.
    pub content: String,
    /// Creation timestamp as UTC Unix milliseconds.
    pub created_at: i64,
    /// Lifecycle status.
    pub status: MessageStatus,
    /// Sanitized failure reason when status is `Error`.
    pub error_message: Option<String>,
}

/// Opaque identifier for an Artifact.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArtifactId(pub String);

/// Opaque identifier for a Memory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemoryId(pub String);

/// Opaque identifier for an Attachment.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AttachmentId(pub String);

/// Kind of an attachment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AttachmentKind {
    /// A file path attachment.
    File,
    /// A pasted clipboard attachment.
    Clipboard,
    /// A memory attachment.
    Memory,
    /// An artifact attachment.
    Artifact,
}

/// A persisted artifact linked to a specific message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Artifact {
    /// App-generated opaque artifact identifier.
    pub id: ArtifactId,
    /// Owning thread identifier.
    pub thread_id: String,
    /// Originating message identifier.
    pub message_id: String,
    /// Artifact title.
    pub title: String,
    /// Artifact content.
    pub content: String,
    /// Creation timestamp as UTC Unix milliseconds.
    pub created_at: i64,
}

/// A persisted core memory piece.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Memory {
    /// App-generated opaque memory identifier.
    pub id: MemoryId,
    /// Memory title.
    pub title: String,
    /// Memory content.
    pub content: String,
    /// Creation timestamp as UTC Unix milliseconds.
    pub created_at: i64,
    /// Last update timestamp as UTC Unix milliseconds.
    pub updated_at: i64,
}

/// A persisted attachment linked to a specific message.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Attachment {
    /// App-generated opaque attachment identifier.
    pub id: AttachmentId,
    /// Owning message identifier.
    pub message_id: String,
    /// Kind of attachment.
    pub kind: AttachmentKind,
    /// Attachment filename or paste name.
    pub name: String,
    /// MIME type of the attachment.
    pub mime_type: String,
    /// Text content for clipboard attachments.
    pub content: Option<String>,
    /// Path for file attachments.
    pub path: Option<String>,
    /// Creation timestamp as UTC Unix milliseconds.
    pub created_at: i64,
}

impl From<DbThread> for Thread {
    fn from(thread: DbThread) -> Self {
        Self {
            id: thread.id,
            title: thread.title,
            created_at: thread.created_at,
            updated_at: thread.updated_at,
            archived: thread.archived,
            provider: thread.provider,
            model: thread.model,
        }
    }
}

impl From<DbMessage> for Message {
    fn from(msg: DbMessage) -> Self {
        Self {
            id: msg.id,
            thread_id: msg.thread_id,
            role: match msg.role.as_str() {
                "user" => MessageRole::User,
                "assistant" => MessageRole::Assistant,
                _ => MessageRole::System,
            },
            content: msg.content,
            created_at: msg.created_at,
            status: match msg.status.as_str() {
                "streaming" => MessageStatus::Streaming,
                "error" => MessageStatus::Error,
                "cancelled" => MessageStatus::Cancelled,
                "failed" => MessageStatus::Failed,
                _ => MessageStatus::Complete,
            },
            error_message: msg.error_message,
        }
    }
}

impl From<DbArtifact> for Artifact {
    fn from(artifact: DbArtifact) -> Self {
        Self {
            id: ArtifactId(artifact.id),
            thread_id: artifact.thread_id,
            message_id: artifact.message_id,
            title: artifact.title,
            content: artifact.content,
            created_at: artifact.created_at,
        }
    }
}

impl From<DbMemory> for Memory {
    fn from(memory: DbMemory) -> Self {
        Self {
            id: MemoryId(memory.id),
            title: memory.title,
            content: memory.content,
            created_at: memory.created_at,
            updated_at: memory.updated_at,
        }
    }
}

impl From<DbAttachment> for Attachment {
    fn from(attachment: DbAttachment) -> Self {
        Self {
            id: AttachmentId(attachment.id),
            message_id: attachment.message_id,
            kind: match attachment.kind.as_str() {
                "clipboard" => AttachmentKind::Clipboard,
                "memory" => AttachmentKind::Memory,
                _ => AttachmentKind::File,
            },
            name: attachment.name,
            mime_type: attachment.mime_type,
            content: attachment.content,
            path: attachment.path,
            created_at: attachment.created_at,
        }
    }
}
